# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Pages/HTML.gitlab-ci.yml

# All available Hugo versions are listed here:
# https://gitlab.com/pages/hugo/container_registry

default:
  image: "rocker/verse:latest"

variables:
  LINUX_PKGS: "git curl unzip"

stages:
  - build

before_script:
  - yum update -y
  - yum install -y ${LINUX_PKGS}
  - git clone https://github.com/quarto-dev/quarto-cli
  - cd quarto-cli
  - bash configure.sh
  - quarto tools install tinytex
  - cd ..

pages:
  stage: build
  script:
    - ls
    - pwd
    - quarto render index.qmd
  artifacts:
    paths:
      - public

