<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.361">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Michael Linke">

<title>Berechnung und Interpretation von Verteilungen</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./Bilder/logo_ub_2021.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./Home.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./Skript_1.1.html" rel="" target="" aria-current="page">
 <span class="menu-text">Der Kurs</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Hintergrund.html" rel="" target="">
 <span class="menu-text">Die Grundidee</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Autoren.html" rel="" target="">
 <span class="menu-text">Die Autor:innen</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/patrickzerrer/R_Hands_on_Book" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Skript_4.1.html">Die ersten Schritte bei der Datenanalyse</a></li><li class="breadcrumb-item"><a href="./Skript_4.4.html">Berechnung und Interpretation von Verteilungen</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Data-Bootcamp: Einführung in R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_1.1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Einführung in R und RStudio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_1.3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Die Logik von Markdown und Quarto</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_1.4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Vorbereiten der R-Umgebung</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Data-Bootcamp: Datensätze</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_2.1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Der Aufbau von Datensätzen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_2.2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Einlesen von Datensätzen in unterschiedlichen Formaten</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_2.3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Der ALLBUS Datensatz</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Data-Bootcamp: Der Umgang mit Daten</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_3.1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Die Kunst vom Umgang mit Daten</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_3.2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Datentypen und -strukturen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_3.3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Selektion, Manipulation und Transformation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_3.4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tabellen und Grafiken in R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Die ersten Schritte bei der Datenanalyse</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_4.1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Häufigkeiten und deren Visualisierung</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_4.2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lageparameter: Modus, Median, Mittelwert</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_4.3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Streuungsmaße: Spannweite, Quartilsabstand, Standartabweichung, Varianz</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_4.4.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Berechnung und Interpretation von Verteilungen</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text">Von einzelnen Antworten zum Index</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_5.1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Die Messung von latenten Variablen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_5.2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Die Faktorenanalyse</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_5.3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reliabilität von Skalen</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
 <span class="menu-text">Das Überprüfen von Unterschieden</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_6.1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bivariate Statistik &amp; Mittelwertvergleiche</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_6.2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bestimmen von Unterschieden in der Varianz mit Kreuztabellen und dem Chi-Quadrat Test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_6.3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Die Bestimmung der Zentrale Tendenz mittels t-Tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_6.4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Die Varianzanalyse</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
 <span class="menu-text">Das Überprüfen von Zusammenhängen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_7.1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Einführung in die Analyse von Zusammenhängen zwischen Variablen - Teil 1: Pearson Chi-Quadrat-Test &amp; *Rangkorrelation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_7.2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Einführung in die Analyse von Zusammenhängen zwischen Variablen - Teil 2: Korrelation &amp; Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_7.3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Zusammenhänge bei mehr als zwei Variablen mit der multiplen Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_7.4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Zusammenhänge bei mehr als zwei Variablen mit der multiplen Regression</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#die-normalverteilung" id="toc-die-normalverteilung" class="nav-link active" data-scroll-target="#die-normalverteilung"><span class="header-section-number">0.1</span> Die Normalverteilung</a>
  <ul class="collapse">
  <li><a href="#berechnung" id="toc-berechnung" class="nav-link" data-scroll-target="#berechnung"><span class="header-section-number">0.1.1</span> Berechnung</a></li>
  </ul></li>
  <li><a href="#visualisierung" id="toc-visualisierung" class="nav-link" data-scroll-target="#visualisierung"><span class="header-section-number">0.2</span> Visualisierung</a></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation"><span class="header-section-number">0.3</span> Interpretation</a></li>
  <li><a href="#was-ist-schon-normal---abweichungen-von-der-normalverteilung" id="toc-was-ist-schon-normal---abweichungen-von-der-normalverteilung" class="nav-link" data-scroll-target="#was-ist-schon-normal---abweichungen-von-der-normalverteilung"><span class="header-section-number">1</span> Was ist schon “normal” - Abweichungen von der Normalverteilung</a>
  <ul class="collapse">
  <li><a href="#lognormalverteilung" id="toc-lognormalverteilung" class="nav-link" data-scroll-target="#lognormalverteilung"><span class="header-section-number">1.1</span> Lognormalverteilung</a>
  <ul class="collapse">
  <li><a href="#berechnung-1" id="toc-berechnung-1" class="nav-link" data-scroll-target="#berechnung-1"><span class="header-section-number">1.1.1</span> Berechnung</a></li>
  <li><a href="#visualisierung-1" id="toc-visualisierung-1" class="nav-link" data-scroll-target="#visualisierung-1"><span class="header-section-number">1.1.2</span> Visualisierung</a></li>
  </ul></li>
  <li><a href="#weibull-verteilung" id="toc-weibull-verteilung" class="nav-link" data-scroll-target="#weibull-verteilung"><span class="header-section-number">1.2</span> Weibull-Verteilung</a>
  <ul class="collapse">
  <li><a href="#berechnung-2" id="toc-berechnung-2" class="nav-link" data-scroll-target="#berechnung-2"><span class="header-section-number">1.2.1</span> Berechnung</a></li>
  <li><a href="#visualisierung-2" id="toc-visualisierung-2" class="nav-link" data-scroll-target="#visualisierung-2"><span class="header-section-number">1.2.2</span> Visualisierung</a></li>
  </ul></li>
  <li><a href="#weitere-verteilungen" id="toc-weitere-verteilungen" class="nav-link" data-scroll-target="#weitere-verteilungen"><span class="header-section-number">1.3</span> Weitere Verteilungen</a>
  <ul class="collapse">
  <li><a href="#binomialverteilung" id="toc-binomialverteilung" class="nav-link" data-scroll-target="#binomialverteilung"><span class="header-section-number">1.3.1</span> Binomialverteilung</a></li>
  <li><a href="#hypergeometrische-verteilung" id="toc-hypergeometrische-verteilung" class="nav-link" data-scroll-target="#hypergeometrische-verteilung"><span class="header-section-number">1.3.2</span> Hypergeometrische Verteilung</a></li>
  <li><a href="#poissonverteilung" id="toc-poissonverteilung" class="nav-link" data-scroll-target="#poissonverteilung"><span class="header-section-number">1.3.3</span> Poissonverteilung</a></li>
  <li><a href="#gleichverteilung" id="toc-gleichverteilung" class="nav-link" data-scroll-target="#gleichverteilung"><span class="header-section-number">1.3.4</span> Gleichverteilung</a></li>
  <li><a href="#exponentialverteilung" id="toc-exponentialverteilung" class="nav-link" data-scroll-target="#exponentialverteilung"><span class="header-section-number">1.3.5</span> Exponentialverteilung</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Berechnung und Interpretation von Verteilungen</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Michael Linke </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Bilder/zemkipatrick_comic_style_cyberpunk_skyline_statistic_normal_dis_4473b399-2f60-47d2-8586-65fc6c1e9325.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Die Verteilung der Stadt, Bild generiert von Midjourney</figcaption>
</figure>
</div>
<p>Wir haben jetzt eine Menge verschiedener Methoden kennengelernt, mit denen wir uns einen Eindruck davon machen können, wie unsere Daten verteilt sind. Um den Begriff der Verteilung an sich haben wir dagegen bis hierher einen Bogen gemacht. Dabei spielt die Art der Verteilung für viele weiterführende Anwendungen eine große Rolle. Manche statistische Verfahren setzen spezifische Verteilungen voraus.</p>
<p>Statistische Verteilungen stellen eine Verbindung her zwischen den empirisch gewonnenen Daten und auf Wahrscheinlichkeit basierenden Aussagen, die wir daraus ableiten wollen. Dabei steht die Frage im Zentrum, mit welcher Wahrscheinlichkeit ein bestimmtes Zufallsereignis eintritt bzw. wie wahrscheinlich es ist, dass eine zufällig gezogene Stichprobe so ausfällt, wie es beobachtet wurde. Können wir annehmen, dass ein Merkmal auf eine bestimmte Weise verteilt ist, können wir eine Prognose abgeben, in welchem Rahmen eine Stichprobe liegen wird. Interessant wird es insbesondere dann, wenn sich nachher zeigt, dass die theoretische Schätzung falsch war und völlig andere Ergebnisse herauskommen. Denn das bedeutet, dass unsere Daten von Faktoren beeinflusst werden, die wir nicht mit eingerechnet haben.</p>
<p>Wir hätten also gerne eine Funktion, die es uns ermöglicht, alle denkbaren Stichproben auf einen Wahrscheinlichkeitswert zwischen 0 und 1 abzubilden. Wenn abzählbar viele Ereignisse eintreten können (z.B. beim Würfeln oder Münzwurf), spricht man von Wahrscheinlichkeitsfunktionen. Bei stetigen Verteilungen (z.B. wenn Zeiträume betrachtet werden) verwendet man den Begriff Dichtefunktion. In beiden Fällen summieren sich alle Funktionswerte zu 1 auf. Eine kumulierte Wahrscheinlichkeits- bzw. Dichtefunktion nennt man Verteilungsfunktion. D.h. bei der Verteilungsfunktion werden die Funktionswerte der Wahrscheinlichkeits summiert bzw. die Dichtefunktion integriert.</p>
<p>Schauen wir uns als Beispiel das Histogramm der Allbus-Einkommensverteilung aus den vorherigen Abschnitten an. Dazu laden wir zunächst die Daten und berechnen einige Parameter:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(<span class="st">"pacman"</span>)) {<span class="fu">install.packages</span>(<span class="st">"pacman"</span>);<span class="fu">library</span>(pacman)}</span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="fu">p_load</span>(tidyverse, ggplot2, haven, dplyr, fitdistrplus)  </span>
<span id="cb1-3"><a href="#cb1-3"></a></span>
<span id="cb1-4"><a href="#cb1-4"></a><span class="fu">theme_set</span>(<span class="fu">theme_classic</span>()) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Dazu laden wir zunächst die Daten und berechnen einige Parameter:</p>
<div class="cell">
<div class="sourceCode cell-code" id="annotated-cell-2"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-2-1"><a href="#annotated-cell-2-1"></a>daten <span class="ot">=</span> haven<span class="sc">::</span><span class="fu">read_dta</span>(<span class="st">"Datensatz/Allbus_2021.dta"</span>) </span>
<span id="annotated-cell-2-2"><a href="#annotated-cell-2-2"></a></span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-2" data-target-annotation="1">1</button><span id="annotated-cell-2-3" class="code-annotation-target"><a href="#annotated-cell-2-3"></a>allbus_df <span class="ot">&lt;-</span> daten <span class="sc">%&gt;%</span></span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-2" data-target-annotation="2">2</button><span id="annotated-cell-2-4" class="code-annotation-target"><a href="#annotated-cell-2-4"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="fu">c</span>(<span class="st">"sex"</span>, <span class="st">"pt12"</span>, <span class="st">"di01a"</span>)) <span class="sc">%&gt;%</span></span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-2" data-target-annotation="3">3</button><span id="annotated-cell-2-5" class="code-annotation-target"><a href="#annotated-cell-2-5"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(<span class="st">"sex"</span>, <span class="st">"pt12"</span>, <span class="st">"di01a"</span>), <span class="sc">~</span> <span class="fu">as.numeric</span>(.))) <span class="sc">%&gt;%</span></span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-2" data-target-annotation="4">4</button><span id="annotated-cell-2-6" class="code-annotation-target"><a href="#annotated-cell-2-6"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(<span class="st">"sex"</span>, <span class="st">"pt12"</span>, <span class="st">"di01a"</span>), <span class="sc">~</span> <span class="fu">ifelse</span>(.<span class="sc">%in%</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">7</span>, <span class="sc">-</span><span class="dv">9</span>, <span class="sc">-</span><span class="dv">11</span>, <span class="sc">-</span><span class="dv">15</span>, <span class="sc">-</span><span class="dv">42</span>, <span class="sc">-</span><span class="dv">50</span> ), <span class="cn">NA</span>,.))) <span class="sc">%&gt;%</span></span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-2" data-target-annotation="5">5</button><span id="annotated-cell-2-7" class="code-annotation-target"><a href="#annotated-cell-2-7"></a>  <span class="fu">na.omit</span>()</span>
<span id="annotated-cell-2-8"><a href="#annotated-cell-2-8"></a></span>
<span id="annotated-cell-2-9"><a href="#annotated-cell-2-9"></a><span class="fu">colnames</span>(allbus_df) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Geschlecht"</span>, <span class="st">"VertrauenBR"</span>, <span class="st">"Einkommen"</span>) <span class="co"># Umbenennen der Spaltennamen</span></span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-hidden code-annotation-container-grid">
<dt data-target-cell="annotated-cell-2" data-target-annotation="1">1</dt>
<dd>
<span data-code-annotation="1" data-code-lines="3" data-code-cell="annotated-cell-2">Wir erstellen ein neues Objekt basierend auf dem Datensatz <code>daten</code></span>
</dd>
<dt data-target-cell="annotated-cell-2" data-target-annotation="2">2</dt>
<dd>
<span data-code-annotation="2" data-code-lines="4" data-code-cell="annotated-cell-2">Wir wählen die Variablen aus</span>
</dd>
<dt data-target-cell="annotated-cell-2" data-target-annotation="3">3</dt>
<dd>
<span data-code-annotation="3" data-code-lines="5" data-code-cell="annotated-cell-2">Die Kombination aus <code>mutate</code> und <code>across</code> ermöglicht es uns die Funktion <code>as.numeric</code> in einer Zeile auf alle zuvor ausgewählten Variablen anzuwenden. Die <code>~</code> gibt den Start der anzuwenden Funktion (hier <code>as.numeric</code> an), der Punkt innerhalb der Klammer der <code>as.numeric</code> Funktion dient als eine Art Platzhalter für die zuvor ausgewählten Variablen</span>
</dd>
<dt data-target-cell="annotated-cell-2" data-target-annotation="4">4</dt>
<dd>
<span data-code-annotation="4" data-code-lines="6" data-code-cell="annotated-cell-2">Wir codieren die unterschiedlichen fehlenden Werte um (aus der Allbus-Dokumentation entnommen). Hierfür greifen wir auf die Funktion <code>if_else</code>zurück. Dabei handelt es sich um ein Entweder-Oder-Befehl. Konkret wird zunächst eine Bedingung geprüft und dann auf dieser Grundlage entweder Option 1 oder Option 2 ausgeführt. Der Punkt vor <code>%in%</code> dient wiederum als Platzhalter, mit dem Ausdruck <code>%in%</code> prüfen wir, ob die nachfolgenden Werte (also c(-9, -11, -42)) in der jeweiligen Variable vorkommen. Hierbei handelt es sich um unsere Bedingung für den Entweder-Oder-Befehl. Wenn einer der Werte aus der geprüften Variable einem der spezifizierten Werte entspricht - also unsere Bedingung erfüllt - wird dieser durch <code>NA</code> ersetzt. Ist die Bedingung nicht erfüllt, wird die andere Option ausgeführt und der bereits existierende Wert wird beibehalten.</span>
</dd>
<dt data-target-cell="annotated-cell-2" data-target-annotation="5">5</dt>
<dd>
<span data-code-annotation="5" data-code-lines="7" data-code-cell="annotated-cell-2">Wir entfernen mit der Funktion <code>na.omit</code> fehlende Werte aus dem Datensatz</span>
</dd>
</dl>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="co"># Funktion zur Berechnung des geometrischen Mittels:</span></span>
<span id="cb2-2"><a href="#cb2-2"></a>geom_mean <span class="ot">=</span> <span class="cf">function</span>(vector){</span>
<span id="cb2-3"><a href="#cb2-3"></a>  <span class="fu">exp</span>(<span class="fu">mean</span>(<span class="fu">log</span>(vector)))</span>
<span id="cb2-4"><a href="#cb2-4"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a>get_mode <span class="ot">=</span> <span class="cf">function</span>(vector){</span>
<span id="cb3-2"><a href="#cb3-2"></a>  frequencies <span class="ot">=</span> <span class="fu">table</span>(vector) </span>
<span id="cb3-3"><a href="#cb3-3"></a>  max_freq <span class="ot">=</span> <span class="fu">max</span>(frequencies)  </span>
<span id="cb3-4"><a href="#cb3-4"></a>  where_max <span class="ot">=</span>frequencies <span class="sc">==</span> max_freq </span>
<span id="cb3-5"><a href="#cb3-5"></a>  modus <span class="ot">=</span> <span class="fu">names</span>(frequencies[where_max]) </span>
<span id="cb3-6"><a href="#cb3-6"></a>  <span class="fu">return</span>(modus)</span>
<span id="cb3-7"><a href="#cb3-7"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a><span class="co"># Berechnung von arithmetischem und geometrischem Mittel, Median, Modus und </span></span>
<span id="cb4-2"><a href="#cb4-2"></a><span class="co"># Standardabweichung:  </span></span>
<span id="cb4-3"><a href="#cb4-3"></a>mean_einkommen <span class="ot">=</span> <span class="fu">mean</span>(allbus_df<span class="sc">$</span>Einkommen)</span>
<span id="cb4-4"><a href="#cb4-4"></a>geom_einkommen <span class="ot">=</span> <span class="fu">geom_mean</span>(allbus_df<span class="sc">$</span>Einkommen <span class="sc">+</span> <span class="dv">42</span>) </span>
<span id="cb4-5"><a href="#cb4-5"></a>median_einkommen <span class="ot">=</span> <span class="fu">median</span>(allbus_df<span class="sc">$</span>Einkommen)</span>
<span id="cb4-6"><a href="#cb4-6"></a>modus_einkommen <span class="ot">=</span> <span class="fu">get_mode</span>(allbus_df<span class="sc">$</span>Einkommen)</span>
<span id="cb4-7"><a href="#cb4-7"></a><span class="fu">sd</span>(allbus_df<span class="sc">$</span>Einkommen)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1610.501</code></pre>
</div>
</div>
<p>Wir plotten zunächst unsere Lageparameter im Histogramm:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a><span class="fu">ggplot</span>(allbus_df, <span class="fu">aes</span>(<span class="at">x =</span> Einkommen)) <span class="sc">+</span> </span>
<span id="cb6-2"><a href="#cb6-2"></a>    <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span><span class="fu">after_stat</span>(density)),</span>
<span id="cb6-3"><a href="#cb6-3"></a>    <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">0</span>, <span class="dv">10000</span>, <span class="at">by =</span> <span class="dv">500</span>), </span>
<span id="cb6-4"><a href="#cb6-4"></a>    <span class="at">colour =</span> <span class="st">"black"</span>, </span>
<span id="cb6-5"><a href="#cb6-5"></a>    <span class="at">fill =</span> <span class="st">"gray"</span>) <span class="sc">+</span></span>
<span id="cb6-6"><a href="#cb6-6"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Einkommen"</span>, <span class="at">y =</span> <span class="st">"Häufigkeit"</span>) <span class="sc">+</span></span>
<span id="cb6-7"><a href="#cb6-7"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mean_einkommen, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb6-8"><a href="#cb6-8"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> median_einkommen, <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb6-9"><a href="#cb6-9"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">as.numeric</span>(modus_einkommen), <span class="at">color =</span> <span class="st">"green"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb6-10"><a href="#cb6-10"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> geom_einkommen, <span class="at">color =</span> <span class="st">"yellow"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Skript_4.4_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Zunächst einmal sieht man, dass sich die Messwerte in einem bestimmten Bereich häufen und eine zumindest annähernde Glockenform aufweisen. Der höchste Punkt deckt sich in etwa mit dem Mittelwert, hier vor allem dem Median (blau) und dem arithmetischen Mittel (rot), während der Modus (grün) etwas abseits liegt. Sie verteilen sich nicht gleichmäßig, was bei Einkommensdaten auch nicht zu erwarten gewesen wäre. So ganz symmetrisch sieht die Verteilung aber auch nicht aus, sondern wirkt etwas nach links gequetscht. Man nennt das auch “rechtsschief” bzw. “linkssteil”. Ein Indiz hierfür ist auch, dass das arithmetische Mittel größer ist als der Median. Das nach rechts gequetschte Gegenstück hieße “linksschief” bzw. “rechtssteil”. Diese Asymmetrie ist auch dadurch bedingt, dass ein erheblicher Teil der Studienteilnehmenden im Datensatz nicht vorkommt. Leute, die keine Angabe gemacht oder angegeben haben, dass sie über kein eigenes Einkommen verfügen, wurden beim Laden herausgefiltert. Die annähernde Glockenform stimmt jedoch hoffnungsvoll, dass der Datensatz mit einer Verteilung zusammenhängt, die in der Statistik von besonderer Bedeutung ist und die wir im Folgenden genauer betrachten werden: Die Normalverteilung.</p>
<section id="die-normalverteilung" class="level2" data-number="0.1">
<h2 data-number="0.1" class="anchored" data-anchor-id="die-normalverteilung"><span class="header-section-number">0.1</span> Die Normalverteilung</h2>
<p>Diese Verteilung ist auch ihrer charakteristischen Form wegen als Glockenkurve oder nach ihrem maßgeblichen Entdecker Carl Friedrich Gauß als Gauß-Verteilung bekannt. Relativ viele andere Verteilungen lassen sich bei ausreichend großer Stichprobengröße mit der Normalverteilung approximieren. Sie ist symmetrisch und der Mittelwert ist ihr Maximum.<br>
Ca. 68% der Werte liegen innerhalb einer Standardabweichung vom Mittelwert entfernt, ca. 95% innerhalb von zwei Standardabweichungen und ca. 99,7%, also fast alle, innerhalb von drei Standardabweichungen.</p>
<section id="berechnung" class="level3" data-number="0.1.1">
<h3 data-number="0.1.1" class="anchored" data-anchor-id="berechnung"><span class="header-section-number">0.1.1</span> Berechnung</h3>
<p>Die Dichtefunktion der Normalverteilung wird folgendermaßen berechnet:</p>
<p><span class="math display">\[
f(x,\mu,\sigma) = \frac{1}{\sigma \sqrt{2 \pi}} \cdot e^{-\frac{(x-\mu)^2}{2 \sigma^2}}
\]</span> Dabei ist <span class="math inline">\(\mu\)</span> der Mittelwert (arithm. Mittel, Median, oder Modus) und <span class="math inline">\(\sigma\)</span> die Standardabweichung.</p>
<p>Bei einer Normalverteilung mit einem Mittelwert von null und einer Varianz von eins spricht man von einer Standardnormalverteilung:</p>
<p><span class="math display">\[
\phi(z) = f(z, 0, 1) = \frac{1}{\sqrt{2 \pi}} \cdot e^{- \frac{z^2}{2}}
\]</span></p>
<p>Normal- aber nicht standardnormal verteilte Werte lassen sich leicht standardisieren, indem man den Mittelwert von ihnen abzieht und das Ergebnis durch die Standardabweichung teilt:</p>
<p><span class="math display">\[
z = \frac{Messwert - Mittelwert}{Standardabweichung} = \frac{x - \mu}{\sigma}
\]</span> <span class="math inline">\(\mu\)</span> kann dabei das arithmetische Mittel, der Median oder der Modus sein.</p>
<p>Der Vollständigkeit halber sei hier auch noch die Formel der Verteilungsfunktion aufgeschrieben:<br>
<span class="math display">\[
F(x, \mu, \sigma) = \frac{1}{2} \left[1 + \text{erf} \left (\frac{x - \mu}{\sigma \sqrt{2}} \right) \right]
\]</span> <span class="math inline">\(erf\)</span> steht für die Gauß’sche Fehlerfunktion.</p>
<p>Da R umfangreiche Funktionalitäten bereitstellt, um diese Verteilungen zu berechnen, ist es an dieser Stelle nicht notwendig, sich diese Formel einzuprägen oder irgendwas damit per Hand zu rechnen. R hat eine ganze Reihe an Verteilungen implementiert und stellt zu jeder davon u.a. vier Funktionen bereit:</p>
<ul>
<li>die Wahrscheinlichkeits-/Dichtefunktion, beginnend mit dem Buchstaben d,</li>
<li>die Verteilungsfunktion, beginnend mit p,</li>
<li>Quantile, beginnend mit q sowie</li>
<li>Zufallszahlen auf Basis der jeweiligen Verteilung, beginnend mit r.</li>
</ul>
</section>
</section>
<section id="visualisierung" class="level2" data-number="0.2">
<h2 data-number="0.2" class="anchored" data-anchor-id="visualisierung"><span class="header-section-number">0.2</span> Visualisierung</h2>
<p>Die folgenden vier Codebeispiele ergeben Visualisierungen der Normalverteilung bei unterschiedlichen Stichprobengrößen von <span class="math inline">\(n = 10\)</span> bis <span class="math inline">\(n = 10000\)</span>. Dabei wird jeweils eine Zufallsstichprobe gezogen und die Verteilung der “Messwerte” als Histogramm ausgegeben. Je größer die Stichprobe, desto stärker sollte sich dabei die Verteilung der Zufallswerte der Dichtefunktion der Normalverteilung annähern, die hier rot dargestellt ist. Mittelwert und Standardabweichung sind so gewählt, dass die Standardnormalverteilung herauskommt. Wiederholen Sie die einzelnen Beispiele mehrmals, dann sollte jedesmal eine andere Stichproben-Verteilung herauskommen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="co">#Zufalls-Stichprobe mit 10 Messwerten:</span></span>
<span id="cb7-2"><a href="#cb7-2"></a></span>
<span id="cb7-3"><a href="#cb7-3"></a>random.data <span class="ot">=</span> <span class="fu">rnorm</span>(<span class="dv">10</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>) <span class="co"># Ziehen der Zufallsstichprobe</span></span>
<span id="cb7-4"><a href="#cb7-4"></a><span class="co"># Histogramm der Verteilung:</span></span>
<span id="cb7-5"><a href="#cb7-5"></a><span class="fu">ggplot</span>(<span class="at">data =</span> <span class="fu">data.frame</span>(<span class="at">x =</span> random.data), <span class="fu">aes</span>(x)) <span class="sc">+</span></span>
<span id="cb7-6"><a href="#cb7-6"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y=</span>..density..), <span class="at">binwidth =</span> <span class="fl">0.1</span>, <span class="at">fill =</span> <span class="st">"gray"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb7-7"><a href="#cb7-7"></a>  <span class="fu">labs</span>(</span>
<span id="cb7-8"><a href="#cb7-8"></a>    <span class="at">title =</span> <span class="st">"Zufallsstichprobe mit 10 Messwerten"</span>, <span class="at">x =</span> <span class="st">"Messwerte"</span>, <span class="at">y =</span> <span class="st">"Häufigkeit"</span>) <span class="sc">+</span></span>
<span id="cb7-9"><a href="#cb7-9"></a><span class="fu">stat_function</span>(<span class="at">fun=</span>dnorm, <span class="at">args=</span><span class="fu">list</span>(<span class="at">mean=</span><span class="dv">0</span>, <span class="at">sd=</span><span class="dv">1</span>), <span class="at">colour=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Skript_4.4_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a>random.data <span class="ot">=</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>) <span class="co"># Ziehen der Zufallsstichprobe</span></span>
<span id="cb8-2"><a href="#cb8-2"></a><span class="co"># Histogramm der Verteilung:</span></span>
<span id="cb8-3"><a href="#cb8-3"></a><span class="fu">ggplot</span>(<span class="at">data =</span> <span class="fu">data.frame</span>(<span class="at">x =</span> random.data), <span class="fu">aes</span>(x)) <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y=</span>..density..), <span class="at">binwidth =</span> <span class="fl">0.1</span>, <span class="at">fill =</span> <span class="st">"gray"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5"></a>  <span class="fu">labs</span>(</span>
<span id="cb8-6"><a href="#cb8-6"></a>    <span class="at">title =</span> <span class="st">"Zufallsstichprobe mit 100 Messwerten"</span>, <span class="at">x =</span> <span class="st">"Messwerte"</span>, <span class="at">y =</span> <span class="st">"Häufigkeit"</span>) <span class="sc">+</span></span>
<span id="cb8-7"><a href="#cb8-7"></a><span class="fu">stat_function</span>(<span class="at">fun=</span>dnorm, <span class="at">args=</span><span class="fu">list</span>(<span class="at">mean=</span><span class="dv">0</span>, <span class="at">sd=</span><span class="dv">1</span>), <span class="at">colour=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Skript_4.4_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a>random.data <span class="ot">=</span> <span class="fu">rnorm</span>(<span class="dv">1000</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>) <span class="co"># Ziehen der Zufallsstichprobe</span></span>
<span id="cb9-2"><a href="#cb9-2"></a><span class="co"># Histogramm der Verteilung:</span></span>
<span id="cb9-3"><a href="#cb9-3"></a><span class="fu">ggplot</span>(<span class="at">data =</span> <span class="fu">data.frame</span>(<span class="at">x =</span> random.data), <span class="fu">aes</span>(x)) <span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y=</span>..density..), <span class="at">binwidth =</span> <span class="fl">0.1</span>, <span class="at">fill =</span> <span class="st">"gray"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb9-5"><a href="#cb9-5"></a>  <span class="fu">labs</span>(</span>
<span id="cb9-6"><a href="#cb9-6"></a>    <span class="at">title =</span> <span class="st">"Zufallsstichprobe mit 1000 Messwerten"</span>, <span class="at">x =</span> <span class="st">"Messwerte"</span>, <span class="at">y =</span> <span class="st">"Häufigkeit"</span>) <span class="sc">+</span></span>
<span id="cb9-7"><a href="#cb9-7"></a><span class="fu">stat_function</span>(<span class="at">fun=</span>dnorm, <span class="at">args=</span><span class="fu">list</span>(<span class="at">mean=</span><span class="dv">0</span>, <span class="at">sd=</span><span class="dv">1</span>), <span class="at">colour=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Skript_4.4_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a>random.data <span class="ot">=</span> <span class="fu">rnorm</span>(<span class="dv">10000</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>) <span class="co"># Ziehen der Zufallsstichprobe</span></span>
<span id="cb10-2"><a href="#cb10-2"></a><span class="co"># Histogramm der Verteilung:</span></span>
<span id="cb10-3"><a href="#cb10-3"></a><span class="fu">ggplot</span>(<span class="at">data =</span> <span class="fu">data.frame</span>(<span class="at">x =</span> random.data), <span class="fu">aes</span>(x)) <span class="sc">+</span></span>
<span id="cb10-4"><a href="#cb10-4"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y=</span>..density..), <span class="at">binwidth =</span> <span class="fl">0.1</span>, <span class="at">fill =</span> <span class="st">"gray"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb10-5"><a href="#cb10-5"></a>  <span class="fu">labs</span>(</span>
<span id="cb10-6"><a href="#cb10-6"></a>    <span class="at">title =</span> <span class="st">"Zufallsstichprobe mit 10000 Messwerten"</span>, <span class="at">x =</span> <span class="st">"Messwerte"</span>, <span class="at">y =</span> <span class="st">"Häufigkeit"</span>) <span class="sc">+</span></span>
<span id="cb10-7"><a href="#cb10-7"></a><span class="fu">stat_function</span>(<span class="at">fun=</span>dnorm, <span class="at">args=</span><span class="fu">list</span>(<span class="at">mean=</span><span class="dv">0</span>, <span class="at">sd=</span><span class="dv">1</span>), <span class="at">colour=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Skript_4.4_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="interpretation" class="level2" data-number="0.3">
<h2 data-number="0.3" class="anchored" data-anchor-id="interpretation"><span class="header-section-number">0.3</span> Interpretation</h2>
<p>Aus der Visualisierung der unterschiedlichen Stichprobengrößen sollte ersichtlich geworden sein, warum ausreichend große Stichproben in der Statistik so wichtig sind. Erst ab einer ausreichend großen Anzahl Messwerten kann überhaupt sicher gesagt werden, ob die Daten einer bestimmten Verteilung folgen.</p>
<p>Wenn man weiß, dass ein bestimmtes Merkmal normalverteilt ist, kann man das nutzen, um mit relativ wenig Aufwand Berechnungen anzustellen. Angenommen, für unsere Einkommensdaten träfe das auch zu, dann könnte man z.B. mithilfe der Normalverteilung ausrechnen, wieviel Prozent der Population theoretisch über maximal 1500 Euro Netto-Einkommen im Monat verfügen. Dazu verwenden wir die Verteilungsfunktion der Normalverteilung, da wir an einem kumulierten Wert interessiert sind, nämlich allen möglichen Einkommenswerten bis maximal 1500 Euro. Wir übergeben der Funktion Mittelwert und Standardabweichung unserer Daten sowie die besagte Einkommensobergrenze:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a>income_mean <span class="ot">=</span> <span class="fu">mean</span>(allbus_df<span class="sc">$</span>Einkommen) </span>
<span id="cb11-2"><a href="#cb11-2"></a>income_sd <span class="ot">=</span> <span class="fu">sd</span>(allbus_df<span class="sc">$</span>Einkommen)</span>
<span id="cb11-3"><a href="#cb11-3"></a>income_median <span class="ot">=</span> <span class="fu">median</span>(allbus_df<span class="sc">$</span>Einkommen)</span>
<span id="cb11-4"><a href="#cb11-4"></a><span class="co"># Die Verteilungsfunktion der Normalverteilung: "p" + "norm": </span></span>
<span id="cb11-5"><a href="#cb11-5"></a><span class="fu">pnorm</span>(<span class="dv">1500</span>, <span class="at">mean=</span>income_mean, <span class="at">sd=</span>income_sd) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2786057</code></pre>
</div>
</div>
<p>Wir bekommen als Ergebnis ca. 0.278. Das vergleichen wir mit dem 27,8%-Quantil unserer Messwerte:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a><span class="fu">quantile</span>(allbus_df<span class="sc">$</span>Einkommen, <span class="at">probs =</span> <span class="fu">c</span>(<span class="fl">0.278</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>27.8% 
 1500 </code></pre>
</div>
</div>
<p>Zur Erinnerung: Das 27,8%-Quantil teilt die untersten 27,8% vom Rest der Messwerte. Interessanterweise liegt die Grenze genau bei 1500 Euro, was exakt der Vorhersage entspricht. Die Übereinstimmung wird aber deutlich schwächer, wenn wir das mit dem (100-27,8)%-Quantil vergleichen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a>q <span class="ot">=</span> <span class="fu">quantile</span>(allbus_df<span class="sc">$</span>Einkommen, <span class="at">probs =</span> <span class="fu">c</span>(<span class="dv">1</span> <span class="sc">-</span> <span class="fl">0.278</span>))</span>
<span id="cb15-2"><a href="#cb15-2"></a>q</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   72.2% 
2977.378 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a><span class="fu">pnorm</span>(<span class="fl">2977.378</span>, <span class="at">mean=</span>income_mean, <span class="at">sd=</span>income_sd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6294329</code></pre>
</div>
</div>
<p>Unsere Messwerte ergeben für das 72,2%-Quantil einen Wert von ca. 2977 Euro. Kalkulieren wir für das selbe Quantil bei der Normalverteilung das zu erwartende Einkommen, werden uns dagegen ca. 3393 Euro angegeben:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1"></a><span class="fu">qnorm</span>(<span class="fl">0.722</span>, <span class="at">mean=</span>income_mean, <span class="at">sd=</span>income_sd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3393.598</code></pre>
</div>
</div>
<p>Die Datenlage weicht folglich um ca. 416 Euro von der theoretischen Annahme ab und fällt deutlich geringer aus. Ein Umstand, der sich auch grafisch widerspiegelt, wenn wir die Normalverteilung in unser Histogramm einzeichnen: Die blaue Kurve markiert den Median als Mittelwert, die rote das arithmetische Mittel, die gelbe das geometrische Mittel.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1"></a><span class="fu">ggplot</span>(allbus_df, <span class="fu">aes</span>(<span class="at">x =</span> Einkommen <span class="sc">+</span> <span class="dv">42</span>)) <span class="sc">+</span> </span>
<span id="cb21-2"><a href="#cb21-2"></a>    <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span><span class="fu">after_stat</span>(density)),</span>
<span id="cb21-3"><a href="#cb21-3"></a>    <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">0</span>, <span class="dv">10000</span>, <span class="at">by =</span> <span class="dv">500</span>), </span>
<span id="cb21-4"><a href="#cb21-4"></a>    <span class="at">colour =</span> <span class="st">"black"</span>, </span>
<span id="cb21-5"><a href="#cb21-5"></a>    <span class="at">fill =</span> <span class="st">"gray"</span>) <span class="sc">+</span></span>
<span id="cb21-6"><a href="#cb21-6"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Einkommen"</span>, <span class="at">y =</span> <span class="st">"Häufigkeit"</span>) <span class="sc">+</span></span>
<span id="cb21-7"><a href="#cb21-7"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> income_mean, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb21-8"><a href="#cb21-8"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> income_median, <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb21-9"><a href="#cb21-9"></a><span class="fu">stat_function</span>(<span class="at">fun=</span>dnorm, <span class="at">args=</span><span class="fu">list</span>(<span class="at">mean=</span>income_mean, <span class="at">sd=</span>income_sd), <span class="at">colour=</span><span class="st">"red"</span>) <span class="sc">+</span>   <span class="co"># Einfügen der Normalcerteilung mit arithm. mittel</span></span>
<span id="cb21-10"><a href="#cb21-10"></a><span class="fu">stat_function</span>(<span class="at">fun=</span>dnorm, <span class="at">args=</span><span class="fu">list</span>(<span class="at">mean=</span>income_median, <span class="at">sd=</span>income_sd), <span class="at">colour=</span><span class="st">"blue"</span>) <span class="sc">+</span>  <span class="co"># Einfügen der NV mit Median</span></span>
<span id="cb21-11"><a href="#cb21-11"></a>  <span class="fu">stat_function</span>(<span class="at">fun=</span>dnorm, <span class="at">args=</span><span class="fu">list</span>(<span class="at">mean=</span><span class="fu">geom_mean</span>(allbus_df<span class="sc">$</span>Einkommen <span class="sc">+</span> <span class="dv">42</span>), <span class="at">sd=</span>income_sd), <span class="at">colour=</span><span class="st">"yellow"</span>) <span class="sc">+</span></span>
<span id="cb21-12"><a href="#cb21-12"></a><span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Einkommen"</span>, <span class="at">y =</span> <span class="st">"Häufigkeit"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Skript_4.4_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Man sieht darin zweierlei: Zum einen gibt es zwar eine gewisse Übereinstimmung, aber doch auch deutliche Unterschiede zwischen den Messwerten und der Normalverteilung und zum zweiten wirken Median und geometrisches Mittel etwas genauer als das arithmetische Mittel. Hier zeigt sich die stärkere Robustheit des Medians gegenüber Ausreißern.</p>
<p>Eine andere Möglichkeit, die Daten mit visuellen Methoden auf Normalverteilung zu prüfen, ist ein sogenannter Q-Q-Plot. Dabei werden die Quantile der theoretischen Verteilung auf einer Achse aufgetragen und die dazu korrespondierenden Quantile der empirischen Daten auf der anderen. Sind die Daten normalverteilt, sollten die Punkte im Plot alle sehr dicht an einer gemeinsamen Linie liegen. Glücklicherweise gibt es auch für diesen Plot eine Funktion:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a><span class="co">#shapiro.test(allbus_messniveau_bsp$di01a)</span></span>
<span id="cb22-2"><a href="#cb22-2"></a><span class="fu">qqnorm</span>(allbus_df<span class="sc">$</span>Einkommen) <span class="co"># Erstellen des Q-Q-Plots</span></span>
<span id="cb22-3"><a href="#cb22-3"></a><span class="fu">qqline</span>(allbus_df<span class="sc">$</span>Einkommen) <span class="co"># Einfügen der Linie, auf der die Punkte liegen sollten</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Skript_4.4_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Wie leicht zu sehen ist, weichen die Daten sehr stark von der Linie ab. Der Bereich unterhalb von ca. 3000 Euro Einkommen scheint zumindest teilweise als normalverteilt interpretierbar zu sein, während für höhere Werte die Ergebnisse massiv abweichen. Allerdings muss auch dazugesagt werden, dass ab 5000 Euro aufwärts die Anzahl an Messwerten deutlich abnimmt.</p>
<p>Eine weitere Möglichkeit, auf Normalverteilung zu testen, sind der Kolmogorov-Smirnov-Test und der Shapiro-Wilk-Test. Diese gehen von der Null-Hypothese aus, dass die Daten normalverteilt sind. Wenn der p-Wert also nahe bei 1 liegt, kann man davon ausgehen, dass die Hypothese bestätigt ist. Wenn der p-Wert gegen 0 geht, deutet das darauf hin, dass die Daten nicht normalverteilt sind. Allerdings sind beide Verfahren nicht unproblematisch, da sie mit zunehmender Stichprobengröße immer anfälliger für Ausreißer werden und die Null-Hypothese eher ablehnen. Der Shapiro-Wilk-Test wird vor allem bei kleinen Stichproben (n &lt; 50) eingesetzt.</p>
<p>Zur Demonstration der R-Funktionalitäten sind die beiden Tests hier aufgeführt, wobei die Größe der Stichprobe eine Ablehnung der Null-Hypothese erwarten lässt. Zunächst der Kolmogorov-Smirnov-Test. Es werden an die Funktion übergeben: Die Stichprobe, die Art der Verteilung, auf die getestet werden soll (hier: die Normalverteilung), der Mittelwert sowie die Standardabweichung der Stichprobe:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1"></a><span class="fu">ks.test</span>(allbus_df<span class="sc">$</span>Einkommen, <span class="st">"pnorm"</span>, <span class="at">mean=</span><span class="fu">mean</span>(allbus_df<span class="sc">$</span>Einkommen), <span class="at">sd=</span><span class="fu">sd</span>(allbus_df<span class="sc">$</span>Einkommen))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Asymptotic one-sample Kolmogorov-Smirnov test

data:  allbus_df$Einkommen
D = 0.14598, p-value = 3.442e-15
alternative hypothesis: two-sided</code></pre>
</div>
</div>
<p>Die Warnung macht uns darauf aufmerksam, dass manche Messwerte im Datensatz mehrfach vorkommen. Der p-Wert ist extrem klein, es wird also angenommen, dass die Daten nicht normalverteilt sind.</p>
<p>Analog dazu der Shapiro-Wilk-Test:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1"></a><span class="fu">shapiro.test</span>(allbus_df<span class="sc">$</span>Einkommen)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  allbus_df$Einkommen
W = 0.83606, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Auch hier ist der p-Wert extrem klein, weshalb auch hier die Annahme abgelehnt wird, dass die Daten normalverteilt sind.</p>
<p>Um die Problematik dieser beiden Tests zu demonstrieren, wird im folgenden Code-Beispiel eine kleine zufällige Teil-Stichprobe aus dem Einkommens-Datensatz gezogen. Führen Sie es mehrmals aus und schauen Sie sich an, wie stark der p-Wert schwankt:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1"></a>sample_einkommen <span class="ot">=</span> <span class="fu">sample</span>(allbus_df<span class="sc">$</span>Einkommen, <span class="at">size=</span><span class="dv">20</span>)</span>
<span id="cb27-2"><a href="#cb27-2"></a><span class="fu">ks.test</span>(sample_einkommen, <span class="st">"pnorm"</span>, <span class="at">mean=</span><span class="fu">mean</span>(allbus_df<span class="sc">$</span>Einkommen), <span class="at">sd=</span><span class="fu">sd</span>(allbus_df<span class="sc">$</span>Einkommen))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Asymptotic one-sample Kolmogorov-Smirnov test

data:  sample_einkommen
D = 0.1849, p-value = 0.5011
alternative hypothesis: two-sided</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1"></a><span class="fu">shapiro.test</span>(sample_einkommen)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  sample_einkommen
W = 0.81054, p-value = 0.001246</code></pre>
</div>
</div>
</section>
<section id="was-ist-schon-normal---abweichungen-von-der-normalverteilung" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Was ist schon “normal” - Abweichungen von der Normalverteilung</h1>
<p>Wenn die Stichprobe keiner Normalverteilung folgt, hat man mehrere Möglichkeiten: Man kann zum einen versuchen, die Daten zu normalisieren, also so zu transformieren, dass sie einer Normalverteilung ähnlicher werden, man kann eine Verteilung wählen, die besser zu den Daten passt und man kann auf Methoden ausweichen, die keine Normalverteilung voraussetzen.</p>
<p>Das folgende Code-Beispiel zeigt eine R-Funktion, die einem helfen kann, eine passende Verteilung zu finden. Sie orientiert sich an den Eigenschaften Schiefe (Skewness) und Wölbung (Kurtosis). Die Schiefe haben wir bereits kennengelernt. Die Wölbung gibt an, wie flach eine Verteilung ist. Wir haben es mit kontinuierlichen Werten zu tun, also setzen wir “discrete” auf FALSE:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1"></a><span class="fu">descdist</span>(allbus_df<span class="sc">$</span>Einkommen, <span class="at">discrete =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Skript_4.4_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>summary statistics
------
min:  -41   max:  14100 
median:  2200 
mean:  2445.346 
estimated sd:  1610.501 
estimated skewness:  2.343418 
estimated kurtosis:  13.47263 </code></pre>
</div>
</div>
<p>Der blaue Punkt gibt an, wo sich die Verteilung unserer empirischen Daten befindet. Er liegt sehr nahe an der Lognormalverteilung, aber auch die Weibull-Verteilung könnte ein passender Kandidat sein.</p>
<section id="lognormalverteilung" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="lognormalverteilung"><span class="header-section-number">1.1</span> Lognormalverteilung</h2>
<p>Wir haben diese Verteilung bereits angesprochen. Für Daten, die einen natürlichen Nullpunkt haben, ist die Lognormalverteilung ein möglicher Kandidat, weil sie nicht symmetrisch ist wie die Normalverteilung. Zur Normalisierung ist sie sehr nützlich. Allerdings sollte man daran denken, dass sie nur mit Werten funktioniert, die größer als Null sind. Man muss also ggf. die Messwerte vorher anpassen.</p>
<section id="berechnung-1" class="level3" data-number="1.1.1">
<h3 data-number="1.1.1" class="anchored" data-anchor-id="berechnung-1"><span class="header-section-number">1.1.1</span> Berechnung</h3>
<p>Die Formel ähnelt der für die Normalverteilung:</p>
<p><span class="math display">\[
f(x;\mu,\sigma) = \frac{1}{x \cdot \sigma \sqrt{2\pi}} \cdot e^{-\frac{(\ln(x)-\mu)^2}{2\sigma^2}}
\]</span></p>
</section>
<section id="visualisierung-1" class="level3" data-number="1.1.2">
<h3 data-number="1.1.2" class="anchored" data-anchor-id="visualisierung-1"><span class="header-section-number">1.1.2</span> Visualisierung</h3>
<p>Schauen wir uns einmal an, wie unsere Einkommensdaten zur Dichtefunktion der Lognormalverteilung passen. Dazu addieren wir zunächst zu jedem Messwert die Zahl 42, damit alle Werte größer Null sind, logarithmieren dann die Messwerte und ermitteln anschließend das arithmetische Mittel und die Standardabweichung:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1"></a>log.allbus.df <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">LogEinkommen=</span><span class="fu">log</span>(allbus_df<span class="sc">$</span>Einkommen <span class="sc">+</span> <span class="dv">42</span>)) </span>
<span id="cb33-2"><a href="#cb33-2"></a>log.mean <span class="ot">=</span> <span class="fu">mean</span>(log.allbus.df<span class="sc">$</span>LogEinkommen) </span>
<span id="cb33-3"><a href="#cb33-3"></a>log.sd <span class="ot">=</span> <span class="fu">sd</span>(log.allbus.df<span class="sc">$</span>LogEinkommen)</span>
<span id="cb33-4"><a href="#cb33-4"></a></span>
<span id="cb33-5"><a href="#cb33-5"></a><span class="fu">cat</span>(<span class="st">"Mittelwert: "</span>, log.mean, <span class="st">"Standardabweichung: "</span>, log.sd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Mittelwert:  7.599235 Standardabweichung:  0.8405187</code></pre>
</div>
</div>
<p>Dann plotten wir das Ergebnis in einem Histogramm, in das wir die theoretische Dichte der Lognormalverteilung eintragen, die unseren Parametern entspricht:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> allbus_df, <span class="fu">aes</span>(<span class="at">x=</span>Einkommen <span class="sc">+</span> <span class="dv">42</span>)) <span class="sc">+</span></span>
<span id="cb35-2"><a href="#cb35-2"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y=</span>..density..), <span class="at">binwidth =</span> <span class="dv">500</span>, <span class="at">fill =</span> <span class="st">"gray"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb35-3"><a href="#cb35-3"></a>  <span class="fu">labs</span>(</span>
<span id="cb35-4"><a href="#cb35-4"></a>    <span class="at">title =</span> <span class="st">"Nettoeinkommen und Lognormalverteilung"</span>, <span class="at">x =</span> <span class="st">"Messwerte"</span>, <span class="at">y =</span> <span class="st">"Dichte"</span>) <span class="sc">+</span></span>
<span id="cb35-5"><a href="#cb35-5"></a><span class="fu">stat_function</span>(<span class="at">fun=</span>dlnorm, <span class="at">args=</span><span class="fu">list</span>(<span class="at">meanlog=</span>log.mean, <span class="at">sdlog=</span>log.sd), <span class="at">colour=</span><span class="st">"red"</span>)  <span class="co">#meanlog=log.mean, sdlog=log.sd</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Skript_4.4_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Die theoretische Verteilung wirkt schiefer als die empirische, aber insgesamt scheint die Übereinstimmung auch visuell größer zu sein als mit der Normalverteilung.</p>
</section>
</section>
<section id="weibull-verteilung" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="weibull-verteilung"><span class="header-section-number">1.2</span> Weibull-Verteilung</h2>
<p>Der zweite Kandidat, der sich bei stetigen, asymmetrischen Verteilungen anbieten kann, ist die Weibull-Verteilung. Sie ist sehr vielseitig, bezogen auf die Formen, die sie annehmen kann und wird deshalb oft für die Kalkulation der Lebensdauer von Maschinenteilen u.ä. verwendet. Allerdings kann sie auch bei der Untersuchung von Einkommensungleichheiten von Bedeutung sein.</p>
<section id="berechnung-2" class="level3" data-number="1.2.1">
<h3 data-number="1.2.1" class="anchored" data-anchor-id="berechnung-2"><span class="header-section-number">1.2.1</span> Berechnung</h3>
<p>Diese Verteilung ist abhängig von einem Streuungsparameter <span class="math inline">\(1 / \lambda\)</span> und dem Formparameter <span class="math inline">\(k\)</span>:</p>
<p>$$ f(x;,k) = ()^{k-1} e<sup>{-(x/</sup>)k}</p>
<p>$$ Durch den Parameter <span class="math inline">\(k\)</span> kann man berücksichtigen, wie sich die Häufigkeit, mit der ein bestimmtes Ereignis auftritt, verändert. Wenn <span class="math inline">\(k = 1\)</span>, geht man davon aus, dass sich die Wahrscheinlichkeit, dass ein Ereignis eintritt, kaum verändert. Für <span class="math inline">\(k &lt; 1\)</span> erwartet man, dass Ereignisse über die Zeit seltener auftreten und für <span class="math inline">\(k &gt; 1\)</span>, dass sie mit der Zeit zunehmen.</p>
</section>
<section id="visualisierung-2" class="level3" data-number="1.2.2">
<h3 data-number="1.2.2" class="anchored" data-anchor-id="visualisierung-2"><span class="header-section-number">1.2.2</span> Visualisierung</h3>
<p>Auf den Netto-Einkommens-Datensatz angewendet, ergibt sich ein Bild, das wie erwartet ähnlich wie die Lognormal-Verteilung wirkt, wenn auch immer noch mit deutlichen Abweichungen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1"></a>fit.weibull <span class="ot">=</span> <span class="fu">fitdist</span>(allbus_df<span class="sc">$</span>Einkommen <span class="sc">+</span> <span class="dv">42</span>, <span class="st">"weibull"</span>)</span>
<span id="cb36-2"><a href="#cb36-2"></a><span class="fu">ggplot</span>(<span class="at">data =</span> allbus_df, <span class="fu">aes</span>(<span class="at">x=</span>Einkommen <span class="sc">+</span> <span class="dv">42</span>)) <span class="sc">+</span></span>
<span id="cb36-3"><a href="#cb36-3"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y=</span>..density..), <span class="at">binwidth =</span> <span class="dv">500</span>, <span class="at">fill =</span> <span class="st">"grey"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb36-4"><a href="#cb36-4"></a>  <span class="fu">labs</span>(</span>
<span id="cb36-5"><a href="#cb36-5"></a>    <span class="at">title =</span> <span class="st">"Netto-Einkommen und Weibull-Verteilung"</span>,</span>
<span id="cb36-6"><a href="#cb36-6"></a>    <span class="at">x =</span> <span class="st">"Messwerte"</span>,</span>
<span id="cb36-7"><a href="#cb36-7"></a>    <span class="at">y =</span> <span class="st">"Dichte"</span></span>
<span id="cb36-8"><a href="#cb36-8"></a>  ) <span class="sc">+</span></span>
<span id="cb36-9"><a href="#cb36-9"></a>  <span class="fu">stat_function</span>(<span class="at">fun=</span>dweibull, <span class="at">args=</span><span class="fu">list</span>(<span class="at">scale=</span>fit.weibull<span class="sc">$</span>estimate[<span class="st">"scale"</span>], <span class="at">shape=</span>fit.weibull<span class="sc">$</span>estimate[<span class="st">"shape"</span>]), <span class="at">colour=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Skript_4.4_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="weitere-verteilungen" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="weitere-verteilungen"><span class="header-section-number">1.3</span> Weitere Verteilungen</h2>
<p>Damit verlassen wir das konkrete Einkommens-Beispiel und die Suche nach Alternativen zur Normalverteilung und schauen uns ein paar weitere Verteilungen an, die je nach Forschungsdesign ebenfalls wichtig sein können.</p>
<section id="binomialverteilung" class="level3" data-number="1.3.1">
<h3 data-number="1.3.1" class="anchored" data-anchor-id="binomialverteilung"><span class="header-section-number">1.3.1</span> Binomialverteilung</h3>
<p>Diese Verteilung basiert auf Zufallsexperimenten, die genau zwei Versuchsausgänge aufweisen, welche sich gegenseitig ausschließen und konstante Wahrscheinlichkeiten für die beiden Ausgänge haben. Die einzelnen Versuche sollen voneinander unabhängig sein.</p>
<p>Ein bekanntes Beispiel für so ein Zufallsexperiment ist der Münzwurf. Anwendungen in der KMW wären etwa Kaufentscheidungen (Ja/Nein) in der Werbewirkungsforschung oder allgemein Interview-Fragen, auf die es nur Ja/Nein-Antworten gibt.</p>
<section id="berechnung-und-visualisierung" class="level4" data-number="1.3.1.1">
<h4 data-number="1.3.1.1" class="anchored" data-anchor-id="berechnung-und-visualisierung"><span class="header-section-number">1.3.1.1</span> Berechnung und Visualisierung</h4>
<p>Bei einer Eintrittswahrscheinlichkeit <span class="math inline">\(p\)</span> für ein bestimmtes Ereignis berechnet sich die Wahrscheinlichkeit, dass das Ereignis nach <span class="math inline">\(n\)</span> Wiederholungen <span class="math inline">\(k\)</span> mal eintritt, mit folgender Formel:</p>
<p><span class="math display">\[
f(k;n,p) = \binom{n}{k} p^k (1-p)^{n-k}
\]</span></p>
<p>Das folgende Beispiel zeigt, wie man in R die Wahrscheinlichkeit berechnet, bei zehn Münzwürfen genau 7 mal Kopf zu werfen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1"></a>n <span class="ot">=</span> <span class="dv">10</span> <span class="co"># Festlegen der Gesamtzahl an Würfen </span></span>
<span id="cb37-2"><a href="#cb37-2"></a>kopf <span class="ot">=</span> <span class="dv">7</span> <span class="co"># Festlegen der Anzahl, wie oft Kopf geworfen werden soll </span></span>
<span id="cb37-3"><a href="#cb37-3"></a>p_kopf <span class="ot">=</span> <span class="fl">0.5</span> <span class="co"># Festlegen der Wahrscheinlichkeit, Kopf zu werfen (hier: 50%)</span></span>
<span id="cb37-4"><a href="#cb37-4"></a>prob <span class="ot">=</span> <span class="fu">dbinom</span>(kopf, <span class="at">size=</span>n, <span class="at">prob=</span>p_kopf) </span>
<span id="cb37-5"><a href="#cb37-5"></a>prob</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1171875</code></pre>
</div>
</div>
</section>
</section>
<section id="hypergeometrische-verteilung" class="level3" data-number="1.3.2">
<h3 data-number="1.3.2" class="anchored" data-anchor-id="hypergeometrische-verteilung"><span class="header-section-number">1.3.2</span> Hypergeometrische Verteilung</h3>
<p>Diese Verteilung kann vorliegen, wenn die Bedingung der Unabhängigkeit der einzelnen Versuche nicht einhaltbar ist.</p>
<section id="berechnung-3" class="level4" data-number="1.3.2.1">
<h4 data-number="1.3.2.1" class="anchored" data-anchor-id="berechnung-3"><span class="header-section-number">1.3.2.1</span> Berechnung</h4>
<p>Es wird wieder von zwei Ereignissen ausgegangen, die eintreten können. Angenommen, eine Grundgesamtheit setzt sich zusammen aus <span class="math inline">\(N + M\)</span> Ereignissen, wobei <span class="math inline">\(M\)</span> und <span class="math inline">\(N\)</span> sich gegenseitig ausschließen. Aus dieser Grundgesamtheit wird nun eine Stichprobe der Größe <span class="math inline">\(k\)</span> gezogen. Dann berechnet sich die Wahrscheinlichkeit, dass sich in der Stichprobe <span class="math inline">\(x\)</span> mal das Ereignis <span class="math inline">\(M\)</span> eintritt, folgendermaßen:</p>
<p><span class="math display">\[
f(x, k, M, N) = \frac{\binom{M}{x} \binom{N}{k-x}}{\binom{N + M}{k}}
\]</span></p>
<p>Machen wir uns das an einem Beispiel deutlich: In einer Stadt mit ca. 600000 Einwohnern sind ca. 2000 Menschen mit HIV infiziert. Wie groß ist die Wahrscheinlichkeit, dass von 50 Leuten, die man bei einem Ausflug in die Stadt zufällig trifft, kein einziger HIV hat?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1"></a>n <span class="ot">=</span> <span class="dv">600000</span> <span class="co"># Grundgesamtheit</span></span>
<span id="cb39-2"><a href="#cb39-2"></a>m <span class="ot">=</span> <span class="dv">2000</span>   <span class="co"># Fälle, die eine bestimmte Merkmalsausprägung aufweisen</span></span>
<span id="cb39-3"><a href="#cb39-3"></a>k <span class="ot">=</span> <span class="dv">50</span>     <span class="co"># Stichprobengröße</span></span>
<span id="cb39-4"><a href="#cb39-4"></a>x <span class="ot">=</span> <span class="dv">0</span>      </span>
<span id="cb39-5"><a href="#cb39-5"></a>prob <span class="ot">=</span> <span class="fu">dhyper</span>(x, m, n, k) </span>
<span id="cb39-6"><a href="#cb39-6"></a>prob</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8467106</code></pre>
</div>
</div>
<p>Das heißt, die Wahrscheinlichkeit, dass mindestens eine Person, der man begegnet, HIV hat, beträgt ca. <span class="math inline">\(1 - 0.8467\)</span>, also ca. 15,33 Prozent.</p>
</section>
</section>
<section id="poissonverteilung" class="level3" data-number="1.3.3">
<h3 data-number="1.3.3" class="anchored" data-anchor-id="poissonverteilung"><span class="header-section-number">1.3.3</span> Poissonverteilung</h3>
<p>Diese Verteilung kann herangezogen werden, wenn es um das durchschnittliche Eintreten bestimmter Ereignisse innerhalb es festen Zeitintervalls geht. Dabei steht <span class="math inline">\(\lambda\)</span> für die Rate, mit der ein Ereignis durchschnittlich eintritt.</p>
<section id="berechnung-4" class="level4" data-number="1.3.3.1">
<h4 data-number="1.3.3.1" class="anchored" data-anchor-id="berechnung-4"><span class="header-section-number">1.3.3.1</span> Berechnung</h4>
<p>Die Poissonverteilung berechnet sich nach folgender Formel:</p>
<p><span class="math display">\[
f(k;\lambda) =  \frac{\lambda^k  }{k!}e^{-\lambda}
\]</span></p>
<p>Dazu wieder ein Beispiel: Eine Nachrichtenagentur veröffentlicht zu einem bestimmten Thema normalerweise 3 Artikel pro Tag. Wie wahrscheinlich ist es, dass sie an einem Tag 7 Artikel zu demselben Thema veröffentlicht?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1"></a>x <span class="ot">=</span> <span class="dv">7</span> </span>
<span id="cb41-2"><a href="#cb41-2"></a>lambda <span class="ot">=</span> <span class="dv">3</span> </span>
<span id="cb41-3"><a href="#cb41-3"></a><span class="fu">dpois</span>(x, lambda)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02160403</code></pre>
</div>
</div>
</section>
</section>
<section id="gleichverteilung" class="level3" data-number="1.3.4">
<h3 data-number="1.3.4" class="anchored" data-anchor-id="gleichverteilung"><span class="header-section-number">1.3.4</span> Gleichverteilung</h3>
<p>Eine Zufallsvariable ist in einem gegebenen Intervall gleichmäßig verteilt. Diese Verteilung ist besonders zur Erzeugung von Zufallszahlen hilfreich.</p>
<section id="berechnung-5" class="level4" data-number="1.3.4.1">
<h4 data-number="1.3.4.1" class="anchored" data-anchor-id="berechnung-5"><span class="header-section-number">1.3.4.1</span> Berechnung</h4>
<p><span class="math display">\[
f(x;min,max) = \begin{cases}
\frac{1}{max-min}, &amp; min \leq x \leq max \\
0, &amp; \text{sonst}
\end{cases}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1"></a><span class="co"># Fünf Zufallszahlen, die im voreingestellten Intervall von 0 bis 1 liegen:</span></span>
<span id="cb43-2"><a href="#cb43-2"></a><span class="fu">runif</span>(<span class="dv">5</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.37430444 0.30606949 0.58539308 0.95486935 0.09363557</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1"></a><span class="co"># Drei Zufallszahlen, die im Intervall von -10 bis 10 liegen:</span></span>
<span id="cb45-2"><a href="#cb45-2"></a><span class="fu">runif</span>(<span class="dv">3</span>, <span class="at">min=</span><span class="sc">-</span><span class="dv">10</span>, <span class="at">max=</span><span class="dv">10</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -6.1896641 -6.4339709  0.3672128</code></pre>
</div>
</div>
</section>
</section>
<section id="exponentialverteilung" class="level3" data-number="1.3.5">
<h3 data-number="1.3.5" class="anchored" data-anchor-id="exponentialverteilung"><span class="header-section-number">1.3.5</span> Exponentialverteilung</h3>
<p>Ähnlich wie die Poissonverteilung, allerdings stetig. Sie ist ein Spezialfall der Weibull-Verteilung und wird z.B. bei der Untersuchung von Zeitabständen eingesetzt.</p>
<section id="berechnung-6" class="level4" data-number="1.3.5.1">
<h4 data-number="1.3.5.1" class="anchored" data-anchor-id="berechnung-6"><span class="header-section-number">1.3.5.1</span> Berechnung</h4>
<p>Im Gegensatz zur etwas vielseitigeren Weibull-Verteilung hat sie einen Parameter weniger, da <span class="math inline">\(k\)</span> unveränderlich gleich 1 ist, geht also von weitgehend gleichmäßig auftretenden Ereignissen aus.</p>
<p><span class="math display">\[
f(k;\lambda) = \begin{cases}
\lambda e^{-\lambda k}, &amp; k \geq 0 \\
0, &amp; x &lt; 0
\end{cases}
\]</span></p>
<p>Beispiel: Eine Nachrichtenagentur berichtet durchschnittlich alle 30 Tage über Proteste und Widerstandsaktionen in einem Land X. Wie wahrscheinlich ist es, dass zwischen den Nachrichten plötzlich nur noch maximal 5 Tage liegen?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1"></a>da <span class="ot">=</span> <span class="dv">30</span> <span class="co"># Durchschnittlicher Abstand in Tagen</span></span>
<span id="cb47-2"><a href="#cb47-2"></a>lambda <span class="ot">=</span> <span class="dv">1</span> <span class="sc">/</span> da</span>
<span id="cb47-3"><a href="#cb47-3"></a>x <span class="ot">=</span> <span class="dv">5</span> </span>
<span id="cb47-4"><a href="#cb47-4"></a>prob <span class="ot">=</span> <span class="fu">pexp</span>(x, <span class="at">rate=</span>lambda)</span>
<span id="cb47-5"><a href="#cb47-5"></a>prob</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1535183</code></pre>
</div>
</div>


</section>
</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Handle positioning of the toggle
      window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
      const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
      for (let i=0; i<annoteTargets.length; i++) {
        const annoteTarget = annoteTargets[i];
        const targetCell = annoteTarget.getAttribute("data-target-cell");
        const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
        const contentFn = () => {
          const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          if (content) {
            const tipContent = content.cloneNode(true);
            tipContent.classList.add("code-annotation-tip-content");
            return tipContent.outerHTML;
          }
        }
        const config = {
          allowHTML: true,
          content: contentFn,
          onShow: (instance) => {
            selectCodeLines(instance.reference);
            instance.reference.classList.add('code-annotation-active');
            window.tippy.hideAll();
          },
          onHide: (instance) => {
            unselectCodeLines();
            instance.reference.classList.remove('code-annotation-active');
          },
          maxWidth: 300,
          delay: [50, 0],
          duration: [200, 0],
          offset: [5, 10],
          arrow: true,
          appendTo: function(el) {
            return el.parentElement.parentElement.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'quarto',
          placement: 'right',
          popperOptions: {
            modifiers: [
            {
              name: 'flip',
              options: {
                flipVariations: false, // true by default
                allowedAutoPlacements: ['right'],
                fallbackPlacements: ['right', 'top', 'top-start', 'top-end'],
              },
            },
            {
              name: 'preventOverflow',
              options: {
                mainAxis: false,
                altAxis: false
              }
            }
            ]        
          }      
        };
        window.tippy(annoteTarget, config); 
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">Copyright 2023, Design by Katharina Maubach &amp; Patrick Zerrer</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>