<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.361">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Katharina Maubach">

<title>Die Varianzanalyse</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Bilder/favicon-32x32.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
<meta property="og:title" content="Die Varianzanalyse">
<meta property="og:description" content="">
<meta property="og:image" content="https://github.com/patrickzerrer/R_Hands_on_Book/Link ergänzen.png">
<meta name="twitter:title" content="Die Varianzanalyse">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://github.com/patrickzerrer/R_Hands_on_Book/Link ergänzen.png">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./Bilder/logo_ub_2021.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./Home.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./Skript_1.1.html" rel="" target="" aria-current="page">
 <span class="menu-text">Der Kurs</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Hintergrund.html" rel="" target="">
 <span class="menu-text">Die Grundidee</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Autoren.html" rel="" target="">
 <span class="menu-text">Die Autor:innen</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/patrickzerrer/R_Hands_on_Book" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Skript_6.1.html">Das Überprüfen von Unterschieden</a></li><li class="breadcrumb-item"><a href="./Skript_6.4.html">Die Varianzanalyse</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Data-Bootcamp: Einführung in R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_1.1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Einführung in R und RStudio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_1.3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Die Logik von Markdown und Quarto</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_1.4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Vorbereiten der R-Umgebung</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Data-Bootcamp: Datensätze</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_2.1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Der Aufbau von Datensätzen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_2.2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Einlesen von Datensätzen in unterschiedlichen Formaten</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_2.3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Der ALLBUS Datensatz</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Data-Bootcamp: Der Umgang mit Daten</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_3.1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Die Kunst vom Umgang mit Daten</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_3.2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Datentypen und -strukturen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_3.3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Selektion, Manipulation und Transformation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_3.4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tabellen und Grafiken in R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Die ersten Schritte bei der Datenanalyse</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_4.1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Häufigkeiten und deren Visualisierung</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_4.2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lageparameter: Modus, Median, Mittelwert</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_4.3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Streuungsmaße: Spannweite, Quartilsabstand, Standartabweichung, Varianz</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_4.4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Berechnung und Interpretation von Verteilungen</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text">Von einzelnen Antworten zum Index</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_5.1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Die Messung von latenten Variablen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_5.2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Die Faktorenanalyse</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_5.3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reliabilität von Skalen</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
 <span class="menu-text">Das Überprüfen von Unterschieden</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_6.1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bivariate Statistik &amp; Mittelwertvergleiche</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_6.2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bestimmen von Unterschieden in der Varianz mit Kreuztabellen und dem Chi-Quadrat Test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_6.3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Die Bestimmung der Zentrale Tendenz mittels t-Tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_6.4.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Die Varianzanalyse</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
 <span class="menu-text">Das Überprüfen von Zusammenhängen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_7.1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Pearson Chi-Quadrat-Test &amp; Rangkorrelation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_7.2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Korrelation &amp; Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_7.3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prüfung der Voraussetzungen bei der linearen Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_7.4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Die multiple Regression</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#datenmanagement" id="toc-datenmanagement" class="nav-link active" data-scroll-target="#datenmanagement"><span class="header-section-number">1</span> Datenmanagement</a></li>
  <li><a href="#voraussetzungsprüfung-für-einfaktorielle-und-mehrfaktorielle-varianzanalyse" id="toc-voraussetzungsprüfung-für-einfaktorielle-und-mehrfaktorielle-varianzanalyse" class="nav-link" data-scroll-target="#voraussetzungsprüfung-für-einfaktorielle-und-mehrfaktorielle-varianzanalyse"><span class="header-section-number">2</span> Voraussetzungsprüfung für einfaktorielle und mehrfaktorielle Varianzanalyse</a>
  <ul class="collapse">
  <li><a href="#überprüfung-der-normalverteilung" id="toc-überprüfung-der-normalverteilung" class="nav-link" data-scroll-target="#überprüfung-der-normalverteilung"><span class="header-section-number">2.1</span> Überprüfung der Normalverteilung</a></li>
  <li><a href="#überprüfung-der-homogenität-der-fehlervarianzen" id="toc-überprüfung-der-homogenität-der-fehlervarianzen" class="nav-link" data-scroll-target="#überprüfung-der-homogenität-der-fehlervarianzen"><span class="header-section-number">2.2</span> Überprüfung der Homogenität der Fehlervarianzen</a></li>
  </ul></li>
  <li><a href="#einfaktorielle-varianzanalyse-ohne-messwiederholung" id="toc-einfaktorielle-varianzanalyse-ohne-messwiederholung" class="nav-link" data-scroll-target="#einfaktorielle-varianzanalyse-ohne-messwiederholung"><span class="header-section-number">3</span> Einfaktorielle Varianzanalyse (ohne Messwiederholung)</a>
  <ul class="collapse">
  <li><a href="#deskriptive-statistiken" id="toc-deskriptive-statistiken" class="nav-link" data-scroll-target="#deskriptive-statistiken"><span class="header-section-number">3.1</span> Deskriptive Statistiken</a></li>
  <li><a href="#durchführen-der-varianzanalyse" id="toc-durchführen-der-varianzanalyse" class="nav-link" data-scroll-target="#durchführen-der-varianzanalyse"><span class="header-section-number">3.2</span> Durchführen der Varianzanalyse</a></li>
  <li><a href="#interpretation-des-outputs" id="toc-interpretation-des-outputs" class="nav-link" data-scroll-target="#interpretation-des-outputs"><span class="header-section-number">3.3</span> Interpretation des Outputs</a></li>
  <li><a href="#posthoctests" id="toc-posthoctests" class="nav-link" data-scroll-target="#posthoctests"><span class="header-section-number">3.4</span> PostHocTests</a></li>
  <li><a href="#interpretation-der-posthoc-tests-und-des-gesamtmodells" id="toc-interpretation-der-posthoc-tests-und-des-gesamtmodells" class="nav-link" data-scroll-target="#interpretation-der-posthoc-tests-und-des-gesamtmodells"><span class="header-section-number">3.5</span> Interpretation der Posthoc-Tests und des Gesamtmodells</a></li>
  <li><a href="#visualisierung-der-gruppenunterschiede-mittels-fehlerbalken" id="toc-visualisierung-der-gruppenunterschiede-mittels-fehlerbalken" class="nav-link" data-scroll-target="#visualisierung-der-gruppenunterschiede-mittels-fehlerbalken"><span class="header-section-number">3.6</span> Visualisierung der Gruppenunterschiede mittels Fehlerbalken</a></li>
  <li><a href="#mehrfaktorielle-varianzanalyse" id="toc-mehrfaktorielle-varianzanalyse" class="nav-link" data-scroll-target="#mehrfaktorielle-varianzanalyse"><span class="header-section-number">3.7</span> Mehrfaktorielle Varianzanalyse</a></li>
  <li><a href="#interpretation-des-outputs-1" id="toc-interpretation-des-outputs-1" class="nav-link" data-scroll-target="#interpretation-des-outputs-1"><span class="header-section-number">3.8</span> Interpretation des Outputs</a>
  <ul class="collapse">
  <li><a href="#post-hoc-tests" id="toc-post-hoc-tests" class="nav-link" data-scroll-target="#post-hoc-tests"><span class="header-section-number">3.8.1</span> Post-Hoc Tests</a></li>
  </ul></li>
  <li><a href="#interpretation-der-posthoc-tests-und-des-gesamtmodells-1" id="toc-interpretation-der-posthoc-tests-und-des-gesamtmodells-1" class="nav-link" data-scroll-target="#interpretation-der-posthoc-tests-und-des-gesamtmodells-1"><span class="header-section-number">3.9</span> Interpretation der Posthoc-Tests und des Gesamtmodells</a>
  <ul class="collapse">
  <li><a href="#visualisierung-der-interaktionen" id="toc-visualisierung-der-interaktionen" class="nav-link" data-scroll-target="#visualisierung-der-interaktionen"><span class="header-section-number">3.9.1</span> ## Visualisierung der Interaktionen</a></li>
  </ul></li>
  <li><a href="#literatur" id="toc-literatur" class="nav-link" data-scroll-target="#literatur"><span class="header-section-number">3.10</span> Literatur</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Die Varianzanalyse</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Katharina Maubach </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Link ergänzen.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Bild</figcaption>
</figure>
</div>
<p>Die Varianzanalyse weitet den Grundgedanken des t-Tests aus, indem sie den simultanen Vergleich von Gruppenmittelwerten über mehr als zwei Gruppen erlaubt. Die einfaktorielle Varianzanalyse definiert die Gruppen dabei anhand eines Faktors (einer unabhängigen Variable), die mehrfaktorielle Varianzanalyse erlaubt mehrere unabhängige kategoriale Variablen im Modell, ist aber nicht mit der multivariaten Varianzanalyse (MANOVA) zu verwechseln, die auch mehrere metrische abhängige Variablen gleichzeitig zulässt. Wenn die Gruppierungsvariable (also die unabhängige Faktor-Variable) mehr als zwei Gruppen unterscheidet, müssen nach der Anova Post-Hoc Tests durchgeführt werden. Denn sollte die Varianzanalyse insgesamt signifikante Werte liefern, wurde zwar festgestellt, dass es überzufällige Unterschiede zwischen den durch die Faktorstufen definierten Gruppen gibt, bei drei und mehr Faktorstufen bleibt aber noch unklar, auf welchen Gruppenunterschieden dieses Ergebnis beruht. Post hoc-Tests liefern spezifischere Informationen dazu, welche Gruppenmittelwerte signifikant voneinander abweichen.</p>
<section id="datenmanagement" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Datenmanagement</h1>
<p>Wir laden zunächst die für dieses Skript benötigten Pakete und legen unseren Grafikhintegrund sowie die Formatierung von Zahlen fest.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(<span class="st">"pacman"</span>)) {<span class="fu">install.packages</span>(<span class="st">"pacman"</span>);<span class="fu">library</span>(pacman)}</span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="fu">p_load</span>(knitr,car, tidyverse, ggplot2, ggpubr, DescTools, dplyr,afex, emmeans, PMCMRplus, sjmisc)</span>
<span id="cb1-3"><a href="#cb1-3"></a></span>
<span id="cb1-4"><a href="#cb1-4"></a><span class="fu">theme_set</span>(<span class="fu">theme_classic</span>())</span>
<span id="cb1-5"><a href="#cb1-5"></a><span class="fu">options</span>(<span class="at">scipen =</span> <span class="dv">999</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Anschließend laden wir unseren Datensatz:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a>daten <span class="ot">=</span> haven<span class="sc">::</span><span class="fu">read_dta</span>(<span class="st">"Datensatz/Allbus_2021.dta"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Um mit dem Datensatz arbeiten zu können benötigen wir einige grundlegende Schritte des Datenmanagements <a href="https://patrickzerrer.github.io/R_Hands_on_Book/Skript_3.3.html">für ausführliche Erklärungen siehe hier</a>. Für die Varianzanalyse möchten wir uns anschauen, wie sich der Gesundheitszustand (und das Alter) der Befragten auf ihr Vertrauen in das Gesundheitswesen auswirkt. Wir nutzen dazu die folgenden Variablen:</p>
<table class="table">
<colgroup>
<col style="width: 20%">
<col style="width: 45%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Variable</th>
<th style="text-align: center;">Beschreibung</th>
<th style="text-align: center;">Ausprägungen</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">hs01</td>
<td style="text-align: center;">Gesundheitszustand der Befragten</td>
<td style="text-align: center;"><p>-42 = Datenfehler</p>
<p>-11 = TNZ Split</p>
<p>-9 = Keine Angabe</p>
<p>1 = Sehr Gut</p>
<p>2 = Gut</p>
<p>3 = Zufriedenstellend</p>
<p>4 = Weniger Gut</p>
<p>5 = Schlecht</p></td>
</tr>
<tr class="even">
<td style="text-align: center;">age</td>
<td style="text-align: center;">Alter der Befragten</td>
<td style="text-align: center;">-32 = Nicht Generierbar</td>
</tr>
<tr class="odd">
<td style="text-align: center;">pt01</td>
<td style="text-align: center;">Vertrauen in das Gesundheitswesen</td>
<td style="text-align: center;"><p>-42 = Datenfehler</p>
<p>-11 = TNZ Split</p>
<p>-9 = Keine Angabe</p>
<p>1 = Gar kein Vertrauen</p>
<p>…</p>
<p>7 = Großes Vertrauen</p></td>
</tr>
</tbody>
</table>
<p>Innerhalb unseres Datenmanagements schließen wir fehlerhafte und fehlende Werte der Variablen sex, agef und pt12 aus und benennen falls nötig die Variablen um:</p>
<div class="cell">
<div class="sourceCode cell-code" id="annotated-cell-3"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-3-1"><a href="#annotated-cell-3-1"></a>daten <span class="ot">&lt;-</span> daten <span class="sc">%&gt;%</span></span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-3" data-target-annotation="1">1</button><span id="annotated-cell-3-2" class="code-annotation-target"><a href="#annotated-cell-3-2"></a>  <span class="fu">filter</span>(., hs01 <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">&amp;</span> pt01 <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">&amp;</span> age <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-3" data-target-annotation="2">2</button><span id="annotated-cell-3-3" class="code-annotation-target"><a href="#annotated-cell-3-3"></a>  <span class="fu">rename</span>(., <span class="at">gesund =</span> hs01,</span>
<span id="annotated-cell-3-4"><a href="#annotated-cell-3-4"></a>            <span class="at">trustges =</span> pt01) <span class="sc">%&gt;%</span> </span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-3" data-target-annotation="3">3</button><span id="annotated-cell-3-5" class="code-annotation-target"><a href="#annotated-cell-3-5"></a>  <span class="fu">mutate</span>(<span class="at">gesund =</span> haven<span class="sc">::</span><span class="fu">as_factor</span>(gesund),</span>
<span id="annotated-cell-3-6"><a href="#annotated-cell-3-6"></a>         <span class="at">trustges =</span> <span class="fu">as.numeric</span>(trustges),</span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-3" data-target-annotation="4">4</button><span id="annotated-cell-3-7" class="code-annotation-target"><a href="#annotated-cell-3-7"></a>         <span class="at">agef =</span> <span class="fu">dicho</span>(age, <span class="at">as.num =</span> T) <span class="sc">%&gt;%</span> <span class="fu">factor</span>(<span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"jung"</span>, <span class="st">"alt"</span>)))</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-hidden code-annotation-container-grid">
<dt data-target-cell="annotated-cell-3" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-3" data-code-annotation="1" data-code-lines="2">Wir schließend fehlende Werte (siehe Tabelle oben aus). Da diese alle negativ sind, können wir einfach alle Werte kleiner als 0 ausschließen.</span>
</dd>
<dt data-target-cell="annotated-cell-3" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-3" data-code-annotation="2" data-code-lines="3">Hier benennen wir die Variablen anders um unsere weitere Arbeit zu vereinfachen.</span>
</dd>
<dt data-target-cell="annotated-cell-3" data-target-annotation="3">3</dt>
<dd>
<span data-code-cell="annotated-cell-3" data-code-annotation="3" data-code-lines="5">Wir speichern die Variablen als Faktoren. Wir nutzen dabei die Funktion as_factor aus dem haven Paket um die Bezeichnungen der Faktorstufen direkt zu übernehmen.</span>
</dd>
<dt data-target-cell="annotated-cell-3" data-target-annotation="4">4</dt>
<dd>
<span data-code-cell="annotated-cell-3" data-code-annotation="4" data-code-lines="7">Wir kodieren die Variable Alter in eine dichotome Variable (jung und alt) um. Die Aufteilung geschieht anhand des Medians der Verteilung.</span>
</dd>
</dl>
</div>
</div>
</section>
<section id="voraussetzungsprüfung-für-einfaktorielle-und-mehrfaktorielle-varianzanalyse" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Voraussetzungsprüfung für einfaktorielle und mehrfaktorielle Varianzanalyse</h1>
<p>Die Varianzanalyse ist ein statistisches Verfahren, dass bestimmte Voraussetzungen bezüglich der abhängigen und unabhängigen Variablen voraussetzt. Dies sind im Überblick:</p>
<ul>
<li>Datenniveau der AV (metrisch) und UV (Faktor)</li>
<li>Normalverteilung der abhängiven Variablen</li>
<li>Homogenität der Fehlervarianzen der unabhängigen Variablen</li>
</ul>
<p>Die meisten Voraussetzungen, die für die Durchführung und Interpretation einer Varianzanalyse erfüllt sein müssen, lassen sich bereits im Vorfeld der eigentlichen Analyse überprüfen. So kann das Messniveau unmitttelbar festgestellt werden. Es gilt für die <em>abhängige (y-)Variable</em> stets, dass sie <em>intervallskaliert</em> sein muss, in R also als ein Vektor vorliegen muss. Die Faktoren bzw. <em>unabhängige(n) (x-) Variable(n)</em> hingegen müssen zwingend nominalskaliert sein und in R demnach als <em>Faktoren</em> vorliegen.</p>
<section id="überprüfung-der-normalverteilung" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="überprüfung-der-normalverteilung"><span class="header-section-number">2.1</span> Überprüfung der Normalverteilung</h2>
<p>Eine weitere wichtige, leicht vorab zu prüfende Bedingung, die für eine Varianzanalyse erfüllt sein muss, ist die <strong>Normalverteilung der abhängigen Variable</strong>. Diese können wir graphisch überprüfen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="annotated-cell-4"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-4-1"><a href="#annotated-cell-4-1"></a><span class="co">#Histogramm ausgeben</span></span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-4" data-target-annotation="1">1</button><span id="annotated-cell-4-2" class="code-annotation-target"><a href="#annotated-cell-4-2"></a><span class="fu">ggplot</span>(daten, <span class="fu">aes</span>(trustges)) <span class="sc">+</span></span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-4" data-target-annotation="2">2</button><span id="annotated-cell-4-3" class="code-annotation-target"><a href="#annotated-cell-4-3"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(count)),</span>
<span id="annotated-cell-4-4"><a href="#annotated-cell-4-4"></a>                 <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"grey"</span>, </span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-4" data-target-annotation="3">3</button><span id="annotated-cell-4-5" class="code-annotation-target"><a href="#annotated-cell-4-5"></a>                 <span class="at">binwidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-4" data-target-annotation="4">4</button><span id="annotated-cell-4-6" class="code-annotation-target"><a href="#annotated-cell-4-6"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Vertrauen in das Gesundheitswesen"</span>,</span>
<span id="annotated-cell-4-7"><a href="#annotated-cell-4-7"></a>         <span class="at">y =</span> <span class="st">""</span>)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-hidden code-annotation-container-grid">
<dt data-target-cell="annotated-cell-4" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-4" data-code-annotation="1" data-code-lines="2">In R nutzen wir das Paket <code>ggplot2</code> von Wickham et al.&nbsp;um ein Histogramm auszugeben. Zunächst müssen wir hier das Paket <code>ggplot2</code> mit dem Befehl <code>ggplot()</code> aufrufen. Anschließend spezifizieren wir innerhalb der Klammer unseren Datensatz (hier <code>daten</code>) und unter aes unsere Variable (hier <code>trustges</code>).</span>
</dd>
<dt data-target-cell="annotated-cell-4" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-4" data-code-annotation="2" data-code-lines="3">Die Spezifizierungen innerhalb der Klammern unseres Histogramms geben an, dass dieses auf den Zahlen unseres Datensatzes beruhen soll <code>(aes(y = after_stat(count))</code>, wir die Außenumrandung schwarz <code>color = black</code> und die Füllfarbe grau wünschen (<code>fill = grey</code>). Diese Spezifikationen sind optional, sorgen jedoch für ein schöneres Aussehen unserer Grafik.</span>
</dd>
<dt data-target-cell="annotated-cell-4" data-target-annotation="3">3</dt>
<dd>
<span data-code-cell="annotated-cell-4" data-code-annotation="3" data-code-lines="5">Mit <code>binwidth = 1</code> verweisen wir hier auf die Breite der Balken unseres Histogramms.</span>
</dd>
<dt data-target-cell="annotated-cell-4" data-target-annotation="4">4</dt>
<dd>
<span data-code-cell="annotated-cell-4" data-code-annotation="4" data-code-lines="6">Für ein verschönertes Aussehen unseres Graphen nutzen wir den Befehl <code>labs</code> um zusätzlich die Achsen zu beschriften.</span>
</dd>
</dl>
</div>
<div class="cell-output-display">
<p><img src="Skript_6.4_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Wir sehen an der Grafik, dass die Variable Vertrauen in das Gesundheitswesen rechtssteil ist, also die Teilnehmer der Befragung eher ein höheres Vertrauen angegeben haben.</p>
<p>Zusätzliche Gewissheit bezüglich des Vorliegens der Normalverteilung bietet der <em>Kolmogorov-Smirnov-Test</em> oder der <em>Shapiro-Wilk-Test</em> (welcher für kleinere Stichproben zwischen 3 und 5000 Fällen konzipiert ist). In R erhalten wir diese Tests mit dem Befehl <code>LillieTest()</code> aus dem Paket <code>DescTools()</code> bzw. <code>shapiro.test()</code>. Beide Tests testen auf Abweichung von der Normalverteilung, demnach sollte diese nicht signifikant ausfallen (da ein signifikanter Test aussagt, dass eine Abweichung von der Normalverteilung besteht, was wir nicht möchten).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="fu">LillieTest</span>(daten<span class="sc">$</span>trustges)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Lilliefors (Kolmogorov-Smirnov) normality test

data:  daten$trustges
D = 0.18718, p-value &lt; 0.00000000000000022</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a><span class="fu">shapiro.test</span>(daten<span class="sc">$</span>trustges)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  daten$trustges
W = 0.92102, p-value &lt; 0.00000000000000022</code></pre>
</div>
</div>
<p>Im vorliegenden Beispiel sind beide Tests signifikant. Allerdings reagieren beide Tests insbesondere bei großen Stichproben sehr sensibel, sodass bereits leichte Abweichungen von der Normalverteilung (etwa durch Ausreißer) die Tests signifikant werden lassen; in diesen Fällen ist es sinnvoll eher auf die graphische Überprüfung (siehe oben) zu schauen. Sowohl der Kolmogorov-Smirnov-Test als auch die Grafik lassen jedoch nicht auf eine perfekte Normalverteilung unserer abhängigen Variablen schließen. In diesem Fall kann die Varianzanalyse dennoch gerechnet werden, da solange die Verteilung nicht extrem steil ist, das Verfahren einigermaßen robust ist. Bei einer sehr starken Verletzung der Normalverteilung müsste ggf. auf <a href="https://patrickzerrer.github.io/R_Hands_on_Book/Skript_6.4.html#exkurs-kruskal-wallis-test">nicht parametrische Tests</a> ausgewichen werden.</p>
</section>
<section id="überprüfung-der-homogenität-der-fehlervarianzen" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="überprüfung-der-homogenität-der-fehlervarianzen"><span class="header-section-number">2.2</span> Überprüfung der Homogenität der Fehlervarianzen</h2>
<p>Die letzte Voraussetzung, die für eine Varianzanalyse erfüllt sein muss, ist die Homogenität der Fehlervarianzen. Um diese zu testen, nutzen wir den Levene-Test auf Varianzhomogenität. Hierfür nutzen wir die Funktion <code>leveneTest()</code>aus dem Paket <code>car</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="annotated-cell-7"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-7-1"><a href="#annotated-cell-7-1"></a><span class="co">#Levene-Test für einfaktorielle Varianzanalyse</span></span>
<span id="annotated-cell-7-2"><a href="#annotated-cell-7-2"></a>daten <span class="sc">%&gt;%</span> </span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-7" data-target-annotation="1">1</button><span id="annotated-cell-7-3" class="code-annotation-target"><a href="#annotated-cell-7-3"></a>  <span class="fu">leveneTest</span>(trustges <span class="sc">~</span> gesund, <span class="at">data =</span> ., <span class="at">center =</span> mean)</span>
<span id="annotated-cell-7-4"><a href="#annotated-cell-7-4"></a></span>
<span id="annotated-cell-7-5"><a href="#annotated-cell-7-5"></a><span class="co">#Levene-Test für mehrfaktorielle Varianzanalyse ausgeben</span></span>
<span id="annotated-cell-7-6"><a href="#annotated-cell-7-6"></a>daten <span class="sc">%&gt;%</span> </span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-7" data-target-annotation="2">2</button><span id="annotated-cell-7-7" class="code-annotation-target"><a href="#annotated-cell-7-7"></a>  <span class="fu">leveneTest</span>(trustges <span class="sc">~</span> gesund<span class="sc">*</span>agef, <span class="at">data =</span> ., <span class="at">center =</span> mean)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-hidden code-annotation-container-grid">
<dt data-target-cell="annotated-cell-7" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-7" data-code-annotation="1" data-code-lines="3">Innerhalb der Klammer müssen wir zunächst unsere abhängige Variable angeben. Danach folgt eine Tilde (~). Im Anschluss müssen wir unsere unabhängige(n) Variablen angeben. Die Tilde sagt quasi, dass unsere abhängige Variable durch unsere unabhängigen Variablen bestimmt wird. Haben wir nur eine abhängige Variable, so geben wir diese an.</span>
</dd>
<dt data-target-cell="annotated-cell-7" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-7" data-code-annotation="2" data-code-lines="7">Haben wir mehrere unabhängige Variablen so können wir diese mit einem * verbinden. Anschließend wird der Test für beide Variablen sowie den Interaktionsterm ausgeben.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = mean)
        Df F value     Pr(&gt;F)    
group    4  5.9109 0.00009738 ***
      3470                       
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Levene's Test for Homogeneity of Variance (center = mean)
        Df F value       Pr(&gt;F)    
group    9  5.2437 0.0000004058 ***
      3465                         
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Wenn der Levene-Test statistisch signifikant ausfällt, sollte die Hypothese homogener Varianzen abgelehnt werden. Falls der Test wie im vorliegenden Fall signifikant ausfällt (da der <code>Pr(&gt;F-Wert)</code> kleiner als 0.05 ist) wurde die Voraussetzung der Homogenität der Fehlervarianzen verletzt. In einem solchen Fall können wir wahlweise auf nicht-parametrische Tests ausweichen, oder die Varianzanalyse dennoch berechnen, wenn wahlweise die deskriptiven Kennwerte keine allzu große Streuung aufweisen, oder wir einen alternativen Posthoc-Test wie Tamhame T2 wählen.</p>
</section>
</section>
<section id="einfaktorielle-varianzanalyse-ohne-messwiederholung" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Einfaktorielle Varianzanalyse (ohne Messwiederholung)</h1>
<p>Nachdem wir die Voraussetzungen geprüft haben, schauen wir uns die einfaktorielle Varianzanalyse an. Im vorliegenden Beispiel möchten wir überprüfen, inwiefern sich der Gesundheitszustand (Variable <code>gesund</code>; Von sehr gut bis schlecht) auf das Vertrauen in das Gesundheitswesen (Variable <code>trustges</code>) auswirkt.</p>
<section id="deskriptive-statistiken" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="deskriptive-statistiken"><span class="header-section-number">3.1</span> Deskriptive Statistiken</h2>
<div class="cell">
<div class="sourceCode cell-code" id="annotated-cell-8"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-8-1"><a href="#annotated-cell-8-1"></a>daten <span class="sc">%&gt;%</span> </span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-8" data-target-annotation="1">1</button><span id="annotated-cell-8-2" class="code-annotation-target"><a href="#annotated-cell-8-2"></a>  <span class="fu">group_by</span>(gesund) <span class="sc">%&gt;%</span></span>
<span id="annotated-cell-8-3"><a href="#annotated-cell-8-3"></a>  <span class="fu">summarise</span>(<span class="at">Mittelwert =</span> <span class="fu">mean</span>(trustges, <span class="at">na.rm =</span> T),</span>
<span id="annotated-cell-8-4"><a href="#annotated-cell-8-4"></a>            <span class="at">Standardabweichung =</span> <span class="fu">sd</span>(trustges, <span class="at">na.rm =</span> T)) <span class="sc">%&gt;%</span> </span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-8" data-target-annotation="2">2</button><span id="annotated-cell-8-5" class="code-annotation-target"><a href="#annotated-cell-8-5"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">2</span>, <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Gesundheitszustand"</span>, <span class="st">"M"</span>, <span class="st">"SD"</span>), <span class="at">caption =</span> <span class="st">"Descriptives Vertrauen"</span>)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-hidden code-annotation-container-grid">
<dt data-target-cell="annotated-cell-8" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-8" data-code-annotation="1" data-code-lines="2,3">Zunächst möchten wir uns anhand von deskriptiven Statistiken einen Überblick über unsere Daten verschaffen. Dafür nutzen wir die <code>group_by</code>-Funktion in Kombination mit der <code>summarise</code>-Funktion.</span>
</dd>
<dt data-target-cell="annotated-cell-8" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-8" data-code-annotation="2" data-code-lines="5">Im nachfolgenden Schritt haben wir mit Hilfe des Befehls <code>kable()</code> aus dem Paket <code>knitr</code> das Aussehen unserer Tabelle verschönert. Dieser Schritt ist optional.</span>
</dd>
</dl>
</div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Descriptives Vertrauen</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Gesundheitszustand</th>
<th style="text-align: right;">M</th>
<th style="text-align: right;">SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">SEHR GUT</td>
<td style="text-align: right;">5.13</td>
<td style="text-align: right;">1.45</td>
</tr>
<tr class="even">
<td style="text-align: left;">GUT</td>
<td style="text-align: right;">4.99</td>
<td style="text-align: right;">1.32</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ZUFRIEDENSTELLEND</td>
<td style="text-align: right;">4.85</td>
<td style="text-align: right;">1.37</td>
</tr>
<tr class="even">
<td style="text-align: left;">WENIGER GUT</td>
<td style="text-align: right;">4.82</td>
<td style="text-align: right;">1.48</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SCHLECHT</td>
<td style="text-align: right;">4.71</td>
<td style="text-align: right;">1.55</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Anhand der deskriptiven Statistiken sehen wir, dass das Vertrauen in das Gesundheitswesen am höchsten ausgeprägt ist, bei Personen die einen guten Gesundheitszustand aufweisen. Ob dieser augenscheinliche Unterschied auch statistisch signifikant ist, möchten wir in einem nächsten Schritt mit der einfaktoriellen ANOVA berechnen.</p>
</section>
<section id="durchführen-der-varianzanalyse" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="durchführen-der-varianzanalyse"><span class="header-section-number">3.2</span> Durchführen der Varianzanalyse</h2>
<p>Zur Berechnung der Varianzanalye nutzen wir die Funktion <code>aov_car</code> aus dem <code>afex</code>-Paket:</p>
<div class="cell">
<div class="sourceCode cell-code" id="annotated-cell-9"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-9-1"><a href="#annotated-cell-9-1"></a><span class="co">#Einfaktorielle ANOVA</span></span>
<span id="annotated-cell-9-2"><a href="#annotated-cell-9-2"></a>fit <span class="ot">&lt;-</span> daten <span class="sc">%&gt;%</span> </span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-9" data-target-annotation="1">1</button><span id="annotated-cell-9-3" class="code-annotation-target"><a href="#annotated-cell-9-3"></a><span class="fu">aov_car</span>(trustges <span class="sc">~</span> gesund <span class="sc">+</span> <span class="fu">Error</span>(respid), <span class="at">data =</span> ., <span class="at">anova_table =</span> <span class="st">"pes"</span>)</span>
<span id="annotated-cell-9-4"><a href="#annotated-cell-9-4"></a></span>
<span id="annotated-cell-9-5"><a href="#annotated-cell-9-5"></a><span class="fu">print</span>(fit)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-hidden code-annotation-container-grid">
<dt data-target-cell="annotated-cell-9" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-9" data-code-annotation="1" data-code-lines="3">Innerhalb der Funktion aov_car müssen wir zunächst die abhängige Variable (<code>trustges</code>) angeben und nach einer Tilde die unabhängige Variabel (<code>gesund</code>). Zudem müssen wir den Zusatz <code>+ Error()</code> nutzen un in der Klammer die Fallid (hier <code>respid</code>) angeben. Alles speichern wir als Objekt <code>fit</code> welches wir anschließend mit <code>print</code> aufrufen.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type 3 tests)

Response: trustges
  Effect      df  MSE        F  pes p.value
1 gesund 4, 3470 1.91 5.46 *** .006   &lt;.001
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '+' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="interpretation-des-outputs" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="interpretation-des-outputs"><span class="header-section-number">3.3</span> Interpretation des Outputs</h2>
<p><em>Effect</em> zeigt die unabhängige Variable des Modells, in diesem Fall die Variable Gesundheitszustand(<code>gesund</code>). Die vier bedeutet, dass hier insgesamt eine Gruppe mit 4 anderen (= fünf Ausprägungen) verglichen wurde.</p>
<p>Über die Werte der zweiten und vierten Spalte, die <em>Freiheitsgrade</em> (<code>df</code>) und die <em>F-Werte</em> (<code>F</code>) ließe sich, wenn man es wollte, der emprische F-Wert in der F-Tabelle, mit dem kritischen Wert (theoretischen F-Wert) vergleichen, um zu prüfen, ob die Nullhypothese, dass keine Unterschiede zwischen den durch die jeweilige Variable definierten Gruppen bestehen, verworfen werden darf. Diesen Aufwand kann man sich allerdings sparen, da R in der Spalte <code>p.value</code> die umgekehrte Aussage macht, dass die Nullhypothese mit der dort berichteten Fehlerwahrscheinlichkeit verworfen werden kann. Beim per Konvention in den Sozialwissenschaften mindestens geltenden Konfidenz-Niveau von 95%, dürfen im Umkehrschluss also für alle Modellterme signifikante Unterschiede in der Grundgesamtheit angenommen werden, die hier einen Wert &lt;.05 aufweisen. Die Spalte ist damit die wichtigste der gesamten Tabelle! Im vorliegenden Datenbeispiel ist demnach ein signifikanter Unterschied des Gesundheitszustandes im Bezug auf das Vertrauen in das Gesundheitswesen ersichtlich.</p>
<p>Die <em>mittlere quadratische Abweichung (MSE)</em> oder Fehlervarianz ist die Summe der Abweichungsquadrate aller Werte vom jeweiligen Gruppenmittelwert. Berechnet wird diese durch die Quadratsummer der Fehlerresiduen geteilt durch die Freiheitsgrade. Sie gibt damit die Varianz innerhalb der einzelnen Gruppen (=nicht erklärte Varianz) wieder.</p>
<p>Die Spalte <em>pes</em> steht für das partielle Eta-Quadrat und gibt die Erklärungskraft der einzelnen Faktoren im Hinblick auf die anhängige Variable an – partiell ist das Eta<sup>2</sup>, da es um die Einflüsse der übrigen Modellgrößen bereinigt ist (für unifaktorielle Analysen wie im vorliegenden Fall ist dies nicht relevant, allerdings für die multifaktorielle ANOVA). Im Datenbeispiel hat demnach der Gesundheitszustand (und damit auch unser Gesamtmodell) eine Erklärkraft von 0.6 Prozent für Unterschiede im Vertrauen auf das Gesundheitssystem. Allerdings wissen wir lediglich, dass sich unsere Gruppen signifikant unterscheiden, nicht jedoch, ob sich alle Gruppen unterscheiden, oder lediglich einzelne. Daher benötigen wir die Posthoc-Tests.</p>
</section>
<section id="posthoctests" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="posthoctests"><span class="header-section-number">3.4</span> PostHocTests</h2>
<p>Zuletzt müssen wir die Posthoc-Tests berechnen, welche uns Aufschluss darüber geben, welche unserer Gruppen sich unterscheiden. Es gibt verschiedene Posthoc-Tests. Grundsätzlich ist der Tukex-Post-Hoc Test zu empfehlen, welche wir über die Funktion <code>emmeans</code>aus dem <code>emmeans</code>-Package aufrufen. Bei fehlender Varianzhomogenität können wir zudem den tamhane-T2 Test nutzen. Dieser basiert allerdings auf einem aov-Objekt, daher geben wir hier mit aov die ANOVA erneut aus. Innerhalb von emmeans können wir hingegen einfach auf unser zuvor spezifiziertes Modell fit verweisen, müssen allerdings noch mit <code>specs=</code> angeben, auf Basis welcher Variablen der Gruppenvergleich durchgeführt werden soll.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a><span class="co">#Tukey Post-Hoc Test</span></span>
<span id="cb9-2"><a href="#cb9-2"></a>emmeans<span class="sc">::</span><span class="fu">emmeans</span>(fit, <span class="at">specs =</span> <span class="st">"gesund"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb9-3"><a href="#cb9-3"></a>  <span class="fu">pairs</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast                        estimate     SE   df t.ratio p.value
 SEHR GUT - GUT                    0.1336 0.0696 3470   1.919  0.3075
 SEHR GUT - ZUFRIEDENSTELLEND      0.2749 0.0734 3470   3.746  0.0017
 SEHR GUT - WENIGER GUT            0.3077 0.0924 3470   3.332  0.0078
 SEHR GUT - SCHLECHT               0.4123 0.1474 3470   2.797  0.0414
 GUT - ZUFRIEDENSTELLEND           0.1413 0.0567 3470   2.490  0.0930
 GUT - WENIGER GUT                 0.1741 0.0798 3470   2.183  0.1864
 GUT - SCHLECHT                    0.2787 0.1398 3470   1.993  0.2696
 ZUFRIEDENSTELLEND - WENIGER GUT   0.0328 0.0831 3470   0.395  0.9949
 ZUFRIEDENSTELLEND - SCHLECHT      0.1374 0.1418 3470   0.969  0.8691
 WENIGER GUT - SCHLECHT            0.1046 0.1524 3470   0.686  0.9595

P value adjustment: tukey method for comparing a family of 5 estimates </code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a><span class="co">#Tamhame T2 Test</span></span>
<span id="cb11-2"><a href="#cb11-2"></a>daten <span class="sc">%&gt;%</span> </span>
<span id="cb11-3"><a href="#cb11-3"></a><span class="fu">aov</span>(trustges <span class="sc">~</span> gesund, <span class="at">data =</span> .) <span class="sc">%&gt;%</span> </span>
<span id="cb11-4"><a href="#cb11-4"></a>  <span class="fu">tamhaneT2Test</span>(.)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  SEHR GUT GUT    ZUFRIEDENSTELLEND WENIGER GUT
GUT               0.4692   -      -                 -          
ZUFRIEDENSTELLEND 0.0029   0.1037 -                 -          
WENIGER GUT       0.0174   0.3186 1.0000            -          
SCHLECHT          0.1230   0.5471 0.9923            0.9996     </code></pre>
</div>
</div>
</section>
<section id="interpretation-der-posthoc-tests-und-des-gesamtmodells" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="interpretation-der-posthoc-tests-und-des-gesamtmodells"><span class="header-section-number">3.5</span> Interpretation der Posthoc-Tests und des Gesamtmodells</h2>
<p>Hier interessiert uns jeweils der p-value (für den Tamhame T2 Test wird uns nur dieser angezeigt). Werte unter .05 bedeuten, dass zwischen diesen Gruppen ein signifikanter Mittelwertunterschied besteht.</p>
<p>In unserem Beispiel sehen wir signifikante Unterschiede zwischen Personen die einen sehr guten Gesundheitszustand aufweisen und Personen, denen es gesundheitlich schlechter geht (Kategorien zufriedenstellender Gesundheitszustand, weniger guter Gesundheitszustand und je nach Test schlechter Gesundheitszustand).</p>
</section>
<section id="visualisierung-der-gruppenunterschiede-mittels-fehlerbalken" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="visualisierung-der-gruppenunterschiede-mittels-fehlerbalken"><span class="header-section-number">3.6</span> Visualisierung der Gruppenunterschiede mittels Fehlerbalken</h2>
<p>Oftmals lohnt es sich, die Ergebnisse der Varianzanalyse auch graphisch darzustellen. Hierzu nutzen wir Fehlerbalkendiagramme:</p>
<div class="cell">
<div class="sourceCode cell-code" id="annotated-cell-12"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-12-1"><a href="#annotated-cell-12-1"></a>daten <span class="sc">%&gt;%</span> </span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-12" data-target-annotation="1">1</button><span id="annotated-cell-12-2" class="code-annotation-target"><a href="#annotated-cell-12-2"></a>  <span class="fu">ggline</span>(<span class="at">x=</span> <span class="st">"gesund"</span>,</span>
<span id="annotated-cell-12-3"><a href="#annotated-cell-12-3"></a>         <span class="at">y =</span> <span class="st">"trustges"</span>,</span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-12" data-target-annotation="2">2</button><span id="annotated-cell-12-4" class="code-annotation-target"><a href="#annotated-cell-12-4"></a>         <span class="at">add =</span> <span class="st">"mean_ci"</span>,</span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-12" data-target-annotation="3">3</button><span id="annotated-cell-12-5" class="code-annotation-target"><a href="#annotated-cell-12-5"></a>         <span class="at">title =</span> <span class="st">"Vertrauen in das Gesundheitswesen"</span>,</span>
<span id="annotated-cell-12-6"><a href="#annotated-cell-12-6"></a>         <span class="at">xlab =</span> <span class="st">"Gesundheitszustand"</span>,</span>
<span id="annotated-cell-12-7"><a href="#annotated-cell-12-7"></a>         <span class="at">ylab =</span> <span class="st">"Vertrauen in das Gesundheitswesen"</span>) <span class="sc">+</span></span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-12" data-target-annotation="4">4</button><span id="annotated-cell-12-8" class="code-annotation-target"><a href="#annotated-cell-12-8"></a>  <span class="fu">rotate_x_text</span>(<span class="dv">45</span>)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-hidden code-annotation-container-grid">
<dt data-target-cell="annotated-cell-12" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-12" data-code-annotation="1" data-code-lines="2,3">Wir wählen auf der x-Achse die Variable <code>gesund</code> aus und auf der y-Achse die Variable <code>trustges</code>.</span>
</dd>
<dt data-target-cell="annotated-cell-12" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-12" data-code-annotation="2" data-code-lines="4">Wir fügen für die jeweiligen Faktorstufen der Variablen <code>gesund</code> die Mittelwerte sowie Konfidenzintervalle hinzu.</span>
</dd>
<dt data-target-cell="annotated-cell-12" data-target-annotation="3">3</dt>
<dd>
<span data-code-cell="annotated-cell-12" data-code-annotation="3" data-code-lines="5,6,7">Wir bennenen unsere Grafik um.</span>
</dd>
<dt data-target-cell="annotated-cell-12" data-target-annotation="4">4</dt>
<dd>
<span data-code-cell="annotated-cell-12" data-code-annotation="4" data-code-lines="8">Da die Labels unserer Faktorstufen sehr lang sind, drehen wir diese um 45 Grad. Dies geschieht mit der Funktion <code>rotate_x_text()</code> aus dem Paket <code>ggpubr</code>.</span>
</dd>
</dl>
</div>
<div class="cell-output-display">
<p><img src="Skript_6.4_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Wie gebe ich die Ergebnisse korrekt an?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Die Ergebnisse der Varianzanalyse werden zumeist in Textform dargestellt. Dafür werden folgende Informationen benötigt:</p>
<p>✅ die Mittelwerte und Standardabweichung der einzelnen Faktorstufen</p>
<p>✅ der df-Wert</p>
<p>✅ der F-Wert</p>
<p>✅ der p-Wert</p>
<p>✅ der pes-Wert</p>
<p>✅ die Posthoc-Test Ergebnisse</p>
<p>Das Format ist üblicherweise:</p>
<blockquote class="blockquote">
<p><strong><em>Beispiel:</em></strong> Personen mit einem sehr guten Gesundheitszustand haben durchschnittlich ein höheres Vertrauen in das Gesundheitswesen (M = 5.13;SD=1.45) als Personen mit einem guten (M = 4.99;SD=1.32), zufriedenstellenden (M = 4.85;SD=1.37), weniger guten (M = 4.82;SD=1.48) oder schlechtem (M = 4.71;SD=1.55) Gesundheitszustand . Der Gesundheitszustand hat dabei einen signifikanten Einfluss auf das Vertrauen in das Gesundheitswesen (F3470)=5,46,p&lt;0,001. Die Effektstärke nach Cohen (1992) liegt bei alpha=0,006 und entspricht einem kleinen Effekt. Post-Hoc Paarvergleiche mit Tamhames ergaben, dass sich der Mittelwert für die Personen mit sehr guten Gesundheitszustand signifikant von den Personen mit zufriedenstellendem (p&lt;0.029) und weniger gutem (p&lt;0.0174) Zustand unterscheidet. Die anderen Gesundheitsgruppen unterscheiden sich hingegen nicht signifikant voneinander.</p>
</blockquote>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exkurs: nicht parametrischer Kruskal Wallis Test
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">

</div>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exkurs: Einfaktorielle Varianzanalyse mit Messwiederholung
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">

</div>
</div>
</div>
</section>
<section id="mehrfaktorielle-varianzanalyse" class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="mehrfaktorielle-varianzanalyse"><span class="header-section-number">3.7</span> Mehrfaktorielle Varianzanalyse</h2>
<p>In der mehrfaktoriellen Varianzanalyse können wir unser Modell aus der einfachen Varianzananlyse erweitern. In diesem Beispiel nutzen wir neben der Variablen zum Gesundheitszustand (<code>gesund</code>) zusätzlich die Variable Alter (<code>agef</code>) um das Vertrauen in das Gesundheitssystem (<code>trustges</code>) vorherzusagen.</p>
<p>Zunächst möchten wir uns anhand von deskriptiven Statistiken einen Überblick über unsere Daten verschaffen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a><span class="co">#Deskriptive Statistiken ausgeben</span></span>
<span id="cb13-2"><a href="#cb13-2"></a>daten <span class="sc">%&gt;%</span> </span>
<span id="cb13-3"><a href="#cb13-3"></a>  <span class="fu">group_by</span>(gesund, agef) <span class="sc">%&gt;%</span> </span>
<span id="cb13-4"><a href="#cb13-4"></a>  <span class="fu">summarise</span>(<span class="at">Mittelwert =</span> <span class="fu">mean</span>(trustges, <span class="at">na.rm =</span> T), </span>
<span id="cb13-5"><a href="#cb13-5"></a>            <span class="at">Standardabweichung =</span> <span class="fu">SD</span>(trustges, <span class="at">na.rm =</span> T)) <span class="sc">%&gt;%</span> </span>
<span id="cb13-6"><a href="#cb13-6"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">2</span>, <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Gesundheitszustand"</span>, <span class="st">"Alter"</span>, <span class="st">"M"</span>, <span class="st">"SD"</span>), <span class="at">caption =</span> <span class="st">"Descriptives Vertrauen"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Descriptives Vertrauen</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Gesundheitszustand</th>
<th style="text-align: left;">Alter</th>
<th style="text-align: right;">M</th>
<th style="text-align: right;">SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">SEHR GUT</td>
<td style="text-align: left;">jung</td>
<td style="text-align: right;">5.15</td>
<td style="text-align: right;">1.42</td>
</tr>
<tr class="even">
<td style="text-align: left;">SEHR GUT</td>
<td style="text-align: left;">alt</td>
<td style="text-align: right;">5.05</td>
<td style="text-align: right;">1.57</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GUT</td>
<td style="text-align: left;">jung</td>
<td style="text-align: right;">4.89</td>
<td style="text-align: right;">1.30</td>
</tr>
<tr class="even">
<td style="text-align: left;">GUT</td>
<td style="text-align: left;">alt</td>
<td style="text-align: right;">5.14</td>
<td style="text-align: right;">1.35</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ZUFRIEDENSTELLEND</td>
<td style="text-align: left;">jung</td>
<td style="text-align: right;">4.58</td>
<td style="text-align: right;">1.42</td>
</tr>
<tr class="even">
<td style="text-align: left;">ZUFRIEDENSTELLEND</td>
<td style="text-align: left;">alt</td>
<td style="text-align: right;">5.01</td>
<td style="text-align: right;">1.31</td>
</tr>
<tr class="odd">
<td style="text-align: left;">WENIGER GUT</td>
<td style="text-align: left;">jung</td>
<td style="text-align: right;">4.50</td>
<td style="text-align: right;">1.60</td>
</tr>
<tr class="even">
<td style="text-align: left;">WENIGER GUT</td>
<td style="text-align: left;">alt</td>
<td style="text-align: right;">4.97</td>
<td style="text-align: right;">1.40</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SCHLECHT</td>
<td style="text-align: left;">jung</td>
<td style="text-align: right;">4.41</td>
<td style="text-align: right;">1.95</td>
</tr>
<tr class="even">
<td style="text-align: left;">SCHLECHT</td>
<td style="text-align: left;">alt</td>
<td style="text-align: right;">4.82</td>
<td style="text-align: right;">1.39</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Zunächst können wir unsere deskriptiven Statistiken betrachten. Hier interessieren uns insbesondere die Mittelwerte für die einzelnen Gruppen. Diese Mittelwerte im Fließtext kurz zu erwähnen, gehört zum „guten Ton” bei der Auswertung einer Varianzanalyse und sollte daher nicht vergessen werden.</p>
<p>Nun können wir unsere ANOVA aufstellen. Es gibt verschiedene Möglichkeiten eine ANOVA zu berechnen, namentlich Type I, II und III. Die einzelnen Typen unterscheiden sich darin, wie die Parameter (insbesondere die Quadratsumme) berechnet wird. Typ I sollte vor allem für ausgeglichene Daten verwendet werden, also Daten bei der für jede Gruppe die gleiche Anzahl an Fällen vorliegen. Ist dies nicht der Fall, sollte Typ II oder Typ III (beispielsweise die Option der Anova in SPSS) verwendet werden. Der typische Befehl für eine Anova in R ist der Befehl <code>aov()</code>. Dieser ist jedoch nur für die Typ I Anova ausgelegt, daher nutzen wir hier erneut den Befehl <code>aov_car()</code> (sowie den distict-Befehl) aus dem <code>afex</code>-Paket welcher standardmäßig die Anova nach Typ III berechnet. Im Prinzip nutzen wir die selbe Syntax wie bei der unifaktoriellen Anova. Wir ergänzen allerdings unsere zweitere unabhängige Variable, beziehungsweise verbinden die beiden unabhängigen Variablen mit einem *. Dadurch erhalten wir sowohl die Werte für die einzelnen Variablen als auch für den Interaktionsterm, also das Zusammenspiel der Variablen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a>fit2 <span class="ot">&lt;-</span> daten <span class="sc">%&gt;%</span> </span>
<span id="cb14-2"><a href="#cb14-2"></a>  afex<span class="sc">::</span><span class="fu">aov_car</span>(trustges <span class="sc">~</span> gesund <span class="sc">*</span> agef <span class="sc">+</span> <span class="fu">Error</span>(respid),</span>
<span id="cb14-3"><a href="#cb14-3"></a>                                     <span class="at">data =</span> ., <span class="at">anova_table =</span> <span class="st">"pes"</span>)</span>
<span id="cb14-4"><a href="#cb14-4"></a><span class="fu">print</span>(fit2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type 3 tests)

Response: trustges
       Effect      df  MSE         F  pes p.value
1      gesund 4, 3465 1.89  7.66 *** .009   &lt;.001
2        agef 1, 3465 1.89 14.63 *** .004   &lt;.001
3 gesund:agef 4, 3465 1.89    2.93 * .003    .020
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '+' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="interpretation-des-outputs-1" class="level2" data-number="3.8">
<h2 data-number="3.8" class="anchored" data-anchor-id="interpretation-des-outputs-1"><span class="header-section-number">3.8</span> Interpretation des Outputs</h2>
<p>Die Erläuterungen der einzelnen Parameter sind gleich zu den Erläuterungen der unifaktoriellen ANOVA, daher werden diese nicht wiederholt. Es zeigt sich, dass der Gesundheitszustand erneut einen signifikanten Einfluss auf das Vertrauen in das Gesundheitswesen hat (welcher im vorliegenden Modell etwas höher mit 0.9 Prozent erklärter Varianz ausfällt). Zusätzlich hat neben der Gesundheitszustand auch das Alter der Befragten einen signifikanten, wenngleich geringeren Einfluss auf das Vertrauen in das Gesundheitswesen. Zudem sehen wir einen signifikanten Einfluss der Interaktion von Alter und Gesundheitszustand (<code>gesund:agef4</code>).</p>
<p>Im Anschluss müssen wir, wie in der univariaten ANOVA, die Posthoc-Tests berechnen (im vorliegenden Fall können wir lediglich den Tukey-Test berechnen, das der Tamhame-Test nur für einfaktorielle Designs funktioniert).</p>
<section id="post-hoc-tests" class="level3" data-number="3.8.1">
<h3 data-number="3.8.1" class="anchored" data-anchor-id="post-hoc-tests"><span class="header-section-number">3.8.1</span> Post-Hoc Tests</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a><span class="co">#Tukey Post-Hoc Test</span></span>
<span id="cb16-2"><a href="#cb16-2"></a>emmeans<span class="sc">::</span><span class="fu">emmeans</span>(fit2, <span class="at">specs =</span> <span class="fu">c</span>(<span class="st">"gesund"</span>, <span class="st">"agef"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb16-3"><a href="#cb16-3"></a>  <span class="fu">pairs</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast                                       estimate     SE   df t.ratio
 SEHR GUT jung - GUT jung                        0.26152 0.0818 3465   3.198
 SEHR GUT jung - ZUFRIEDENSTELLEND jung          0.56895 0.0971 3465   5.861
 SEHR GUT jung - WENIGER GUT jung                0.65126 0.1406 3465   4.632
 SEHR GUT jung - SCHLECHT jung                   0.73979 0.2727 3465   2.713
 SEHR GUT jung - SEHR GUT alt                    0.09591 0.1434 3465   0.669
 SEHR GUT jung - GUT alt                         0.00434 0.0871 3465   0.050
 SEHR GUT jung - ZUFRIEDENSTELLEND alt           0.13472 0.0858 3465   1.570
 SEHR GUT jung - WENIGER GUT alt                 0.17433 0.1083 3465   1.609
 SEHR GUT jung - SCHLECHT alt                    0.32668 0.1692 3465   1.931
 GUT jung - ZUFRIEDENSTELLEND jung               0.30743 0.0853 3465   3.602
 GUT jung - WENIGER GUT jung                     0.38974 0.1328 3465   2.935
 GUT jung - SCHLECHT jung                        0.47827 0.2688 3465   1.779
 GUT jung - SEHR GUT alt                        -0.16560 0.1357 3465  -1.220
 GUT jung - GUT alt                             -0.25718 0.0738 3465  -3.484
 GUT jung - ZUFRIEDENSTELLEND alt               -0.12680 0.0723 3465  -1.755
 GUT jung - WENIGER GUT alt                     -0.08719 0.0980 3465  -0.890
 GUT jung - SCHLECHT alt                         0.06517 0.1628 3465   0.400
 ZUFRIEDENSTELLEND jung - WENIGER GUT jung       0.08231 0.1427 3465   0.577
 ZUFRIEDENSTELLEND jung - SCHLECHT jung          0.17084 0.2738 3465   0.624
 ZUFRIEDENSTELLEND jung - SEHR GUT alt          -0.47303 0.1455 3465  -3.252
 ZUFRIEDENSTELLEND jung - GUT alt               -0.56461 0.0905 3465  -6.240
 ZUFRIEDENSTELLEND jung - ZUFRIEDENSTELLEND alt -0.43423 0.0892 3465  -4.868
 ZUFRIEDENSTELLEND jung - WENIGER GUT alt       -0.39462 0.1111 3465  -3.553
 ZUFRIEDENSTELLEND jung - SCHLECHT alt          -0.24226 0.1710 3465  -1.417
 WENIGER GUT jung - SCHLECHT jung                0.08853 0.2921 3465   0.303
 WENIGER GUT jung - SEHR GUT alt                -0.55535 0.1775 3465  -3.129
 WENIGER GUT jung - GUT alt                     -0.64692 0.1361 3465  -4.752
 WENIGER GUT jung - ZUFRIEDENSTELLEND alt       -0.51655 0.1353 3465  -3.818
 WENIGER GUT jung - WENIGER GUT alt             -0.47693 0.1506 3465  -3.167
 WENIGER GUT jung - SCHLECHT alt                -0.32458 0.1989 3465  -1.632
 SCHLECHT jung - SEHR GUT alt                   -0.64387 0.2935 3465  -2.194
 SCHLECHT jung - GUT alt                        -0.73545 0.2704 3465  -2.719
 SCHLECHT jung - ZUFRIEDENSTELLEND alt          -0.60507 0.2700 3465  -2.241
 SCHLECHT jung - WENIGER GUT alt                -0.56546 0.2780 3465  -2.034
 SCHLECHT jung - SCHLECHT alt                   -0.41311 0.3069 3465  -1.346
 SEHR GUT alt - GUT alt                         -0.09158 0.1390 3465  -0.659
 SEHR GUT alt - ZUFRIEDENSTELLEND alt            0.03880 0.1382 3465   0.281
 SEHR GUT alt - WENIGER GUT alt                  0.07841 0.1532 3465   0.512
 SEHR GUT alt - SCHLECHT alt                     0.23077 0.2009 3465   1.149
 GUT alt - ZUFRIEDENSTELLEND alt                 0.13038 0.0782 3465   1.666
 GUT alt - WENIGER GUT alt                       0.16999 0.1025 3465   1.659
 GUT alt - SCHLECHT alt                          0.32234 0.1655 3465   1.948
 ZUFRIEDENSTELLEND alt - WENIGER GUT alt         0.03961 0.1013 3465   0.391
 ZUFRIEDENSTELLEND alt - SCHLECHT alt            0.19197 0.1648 3465   1.165
 WENIGER GUT alt - SCHLECHT alt                  0.15236 0.1776 3465   0.858
 p.value
  0.0453
  &lt;.0001
  0.0002
  0.1688
  0.9997
  1.0000
  0.8626
  0.8440
  0.6480
  0.0119
  0.0964
  0.7484
  0.9693
  0.0179
  0.7635
  0.9968
  1.0000
  0.9999
  0.9998
  0.0384
  &lt;.0001
  0.0001
  0.0141
  0.9222
  1.0000
  0.0558
  0.0001
  0.0053
  0.0498
  0.8328
  0.4609
  0.1661
  0.4288
  0.5748
  0.9428
  0.9997
  1.0000
  1.0000
  0.9795
  0.8145
  0.8183
  0.6362
  1.0000
  0.9775
  0.9976

P value adjustment: tukey method for comparing a family of 10 estimates </code></pre>
</div>
</div>
</section>
</section>
<section id="interpretation-der-posthoc-tests-und-des-gesamtmodells-1" class="level2" data-number="3.9">
<h2 data-number="3.9" class="anchored" data-anchor-id="interpretation-der-posthoc-tests-und-des-gesamtmodells-1"><span class="header-section-number">3.9</span> Interpretation der Posthoc-Tests und des Gesamtmodells</h2>
<section id="visualisierung-der-interaktionen" class="level3" data-number="3.9.1">
<h3 data-number="3.9.1" class="anchored" data-anchor-id="visualisierung-der-interaktionen"><span class="header-section-number">3.9.1</span> ## Visualisierung der Interaktionen</h3>
<p>Um einen möglichen Interaktionseffekt auch anschaulich vermitteln bzw. oft auch verstehen zu können, empfiehlt es sich, diesen als Diagramm darzustellen. Hierzu nutzen wir die Pakete <code>emmeans</code> und <code>ggplot2</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a><span class="co">#Interaktionsplot ausgeben</span></span>
<span id="cb18-2"><a href="#cb18-2"></a><span class="fu">emmip</span>(fit2, agef <span class="sc">~</span> gesund) <span class="sc">+</span> </span>
<span id="cb18-3"><a href="#cb18-3"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Geschätzes Randmittel von Vertrauen in das Gesundheitswesen"</span>, </span>
<span id="cb18-4"><a href="#cb18-4"></a>       <span class="at">y =</span> <span class="st">"Geschätzte Randmittel"</span>,</span>
<span id="cb18-5"><a href="#cb18-5"></a>       <span class="at">x =</span> <span class="st">"Gesundheitszustand"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Skript_6.4_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1"></a><span class="fu">emmip</span>(fit2, gesund <span class="sc">~</span> agef) <span class="sc">+</span> </span>
<span id="cb19-2"><a href="#cb19-2"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Geschätzes Randmittel von Vertrauen in das Gesundheitswesen"</span>, </span>
<span id="cb19-3"><a href="#cb19-3"></a>       <span class="at">y =</span> <span class="st">"Geschätzte Randmittel"</span>,</span>
<span id="cb19-4"><a href="#cb19-4"></a>       <span class="at">x =</span> <span class="st">"Alter der Befragten"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Skript_6.4_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="literatur" class="level2" data-number="3.10">
<h2 data-number="3.10" class="anchored" data-anchor-id="literatur"><span class="header-section-number">3.10</span> Literatur</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Literatur und Beispiele aus der Praxis
</div>
</div>
<div class="callout-body-container callout-body">
<p>Wir empfehlen euch folgende Lehrbücher, falls ihr weiterführende Informationen braucht.</p>
<blockquote class="blockquote">
<p>📖 Field, Z., Miles, J., &amp; Field, A. (2012). Discovering statistics using R. Discovering statistics using r, 1-992. <a href="https://suche.suub.uni-bremen.de/peid=B68436977&amp;LAN=DE&amp;CID=7699632&amp;index=L&amp;Hitnr=1&amp;dtyp=D&amp;rtyp=a&amp;Exemplar=1">Link</a></p>
</blockquote>
<blockquote class="blockquote">
<p>📖 Gehrau, V., Maubach, K., &amp; Fujarski, S. (2022). Einfache Datenauswertung mit R. <a href="https://link.springer.com/book/10.1007/978-3-658-34285-2">Link</a></p>
</blockquote>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Handle positioning of the toggle
      window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
      const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
      for (let i=0; i<annoteTargets.length; i++) {
        const annoteTarget = annoteTargets[i];
        const targetCell = annoteTarget.getAttribute("data-target-cell");
        const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
        const contentFn = () => {
          const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          if (content) {
            const tipContent = content.cloneNode(true);
            tipContent.classList.add("code-annotation-tip-content");
            return tipContent.outerHTML;
          }
        }
        const config = {
          allowHTML: true,
          content: contentFn,
          onShow: (instance) => {
            selectCodeLines(instance.reference);
            instance.reference.classList.add('code-annotation-active');
            window.tippy.hideAll();
          },
          onHide: (instance) => {
            unselectCodeLines();
            instance.reference.classList.remove('code-annotation-active');
          },
          maxWidth: 300,
          delay: [50, 0],
          duration: [200, 0],
          offset: [5, 10],
          arrow: true,
          appendTo: function(el) {
            return el.parentElement.parentElement.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'quarto',
          placement: 'right',
          popperOptions: {
            modifiers: [
            {
              name: 'flip',
              options: {
                flipVariations: false, // true by default
                allowedAutoPlacements: ['right'],
                fallbackPlacements: ['right', 'top', 'top-start', 'top-end'],
              },
            },
            {
              name: 'preventOverflow',
              options: {
                mainAxis: false,
                altAxis: false
              }
            }
            ]        
          }      
        };
        window.tippy(annoteTarget, config); 
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Copyright 2023, Design by Katharina Maubach &amp; Patrick Zerrer</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right"><img src="Bilder/Logo_Stiftung_Hochschullehre_pos.jpg" class="img-fluid" width="120"> <img src="Bilder/Skill_UB_Icons_1_quer__blau.jpeg" class="img-fluid" width="120"></div>
  </div>
</footer>



</body></html>