<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.361">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Stephanie Geise">

<title>Die multiple Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
<meta property="og:title" content="Die multiple Regression">
<meta property="og:description" content="">
<meta property="og:image" content="https://github.com/patrickzerrer/R_Hands_on_Book/Bilder/zemkipatrick_comic_style_a_factory_hall_full_of_machines_people_e0656824-d2d4-43ae-bebf-110186024d79.png">
<meta property="og:image:height" content="816">
<meta property="og:image:width" content="1456">
<meta name="twitter:title" content="Die multiple Regression">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://github.com/patrickzerrer/R_Hands_on_Book/Bilder/zemkipatrick_comic_style_a_factory_hall_full_of_machines_people_e0656824-d2d4-43ae-bebf-110186024d79.png">
<meta name="twitter:image-height" content="816">
<meta name="twitter:image-width" content="1456">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./Bilder/logo_ub_2021.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./Home.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./Skript_1.1.html" rel="" target="" aria-current="page">
 <span class="menu-text">Der Kurs</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Hintergrund.html" rel="" target="">
 <span class="menu-text">Die Grundidee</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Autoren.html" rel="" target="">
 <span class="menu-text">Die Autor:innen</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/patrickzerrer/R_Hands_on_Book" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Skript_7.1.html">Das Überprüfen von Zusammenhängen</a></li><li class="breadcrumb-item"><a href="./Skript_7.4.html">Die multiple Regression</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Data-Bootcamp: Einführung in R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_1.1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Einführung in R und RStudio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_1.3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Die Logik von Markdown und Quarto</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_1.4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Vorbereiten der R-Umgebung</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Data-Bootcamp: Datensätze</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_2.1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Der Aufbau von Datensätzen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_2.2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Einlesen von Datensätzen in unterschiedlichen Formaten</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_2.3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Der ALLBUS Datensatz</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Data-Bootcamp: Der Umgang mit Daten</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_3.1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Die Kunst vom Umgang mit Daten</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_3.2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Datentypen und -strukturen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_3.3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Selektion, Manipulation und Transformation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_3.4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tabellen und Grafiken in R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Die ersten Schritte bei der Datenanalyse</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_4.1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Häufigkeiten und deren Visualisierung</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_4.2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lageparameter: Modus, Median, Mittelwert</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_4.3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Streuungsmaße: Spannweite, Quartilsabstand, Standartabweichung, Varianz</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_4.4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Berechnung und Interpretation von Verteilungen</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text">Von einzelnen Antworten zum Index</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_5.1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Die Messung von latenten Variablen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_5.2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Die Faktorenanalyse</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_5.3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reliabilität von Skalen</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
 <span class="menu-text">Das Überprüfen von Unterschieden</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_6.1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bivariate Statistik &amp; Mittelwertvergleiche</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_6.2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bestimmen von Unterschieden in der Varianz mit Kreuztabellen und dem Chi-Quadrat Test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_6.3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Die Bestimmung der Zentrale Tendenz mittels t-Tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_6.4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Die Varianzanalyse</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
 <span class="menu-text">Das Überprüfen von Zusammenhängen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_7.1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Pearson Chi-Quadrat-Test &amp; Rangkorrelation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_7.2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Korrelation &amp; Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_7.3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prüfung der Voraussetzungn bei der linearen Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Skript_7.4.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Die multiple Regression</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#erinnerung-einfache-lineare-regression-mit-alter-als-uv-und-tv-nutzung-als-av-mit-lm-linear-models" id="toc-erinnerung-einfache-lineare-regression-mit-alter-als-uv-und-tv-nutzung-als-av-mit-lm-linear-models" class="nav-link active" data-scroll-target="#erinnerung-einfache-lineare-regression-mit-alter-als-uv-und-tv-nutzung-als-av-mit-lm-linear-models"><span class="header-section-number">1</span> Erinnerung: Einfache lineare Regression mit Alter als UV und TV-Nutzung als AV mit lm (=linear models)</a></li>
  <li><a href="#multiple-lineare-regression-mit-alter-bildung-sowie-vertrauen-ins-fernsehen-als-uv-und-tv-nutzung-als-av-mit-lm-linear-models" id="toc-multiple-lineare-regression-mit-alter-bildung-sowie-vertrauen-ins-fernsehen-als-uv-und-tv-nutzung-als-av-mit-lm-linear-models" class="nav-link" data-scroll-target="#multiple-lineare-regression-mit-alter-bildung-sowie-vertrauen-ins-fernsehen-als-uv-und-tv-nutzung-als-av-mit-lm-linear-models"><span class="header-section-number">2</span> Multiple lineare Regression mit Alter, Bildung sowie Vertrauen ins Fernsehen als UV und TV-Nutzung als AV mit lm (=linear models)</a>
  <ul class="collapse">
  <li><a href="#inhaltliche-interpretation-des-outputs-was-bedeutet-das-ergebnis" id="toc-inhaltliche-interpretation-des-outputs-was-bedeutet-das-ergebnis" class="nav-link" data-scroll-target="#inhaltliche-interpretation-des-outputs-was-bedeutet-das-ergebnis"><span class="header-section-number">2.1</span> Inhaltliche Interpretation des Outputs: Was bedeutet das Ergebnis?</a></li>
  <li><a href="#zusätzliche-voraussetzungsprüfung-bei-der-multiplen-linearen-regression-liegt-multikollinearität-vor" id="toc-zusätzliche-voraussetzungsprüfung-bei-der-multiplen-linearen-regression-liegt-multikollinearität-vor" class="nav-link" data-scroll-target="#zusätzliche-voraussetzungsprüfung-bei-der-multiplen-linearen-regression-liegt-multikollinearität-vor"><span class="header-section-number">2.2</span> Zusätzliche Voraussetzungsprüfung bei der multiplen linearen Regression: Liegt Multikollinearität vor?</a></li>
  <li><a href="#vorhersage-des-multivariaten-modells-für-die-tägliche-tv-nutzung-durch-alter-bildung-und-vertrauen-in-das-fernsehen" id="toc-vorhersage-des-multivariaten-modells-für-die-tägliche-tv-nutzung-durch-alter-bildung-und-vertrauen-in-das-fernsehen" class="nav-link" data-scroll-target="#vorhersage-des-multivariaten-modells-für-die-tägliche-tv-nutzung-durch-alter-bildung-und-vertrauen-in-das-fernsehen"><span class="header-section-number">2.3</span> Vorhersage des multivariaten Modells für die tägliche TV-Nutzung durch Alter, Bildung und Vertrauen in das Fernsehen</a></li>
  <li><a href="#multiple-regression-mit-dummy-codierung-der-kategorialen-variable-sex" id="toc-multiple-regression-mit-dummy-codierung-der-kategorialen-variable-sex" class="nav-link" data-scroll-target="#multiple-regression-mit-dummy-codierung-der-kategorialen-variable-sex"><span class="header-section-number">2.4</span> Multiple Regression mit Dummy-Codierung der kategorialen Variable “sex”</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Die multiple Regression</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Stephanie Geise </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Bilder/zemkipatrick_comic_style_a_factory_hall_full_of_machines_people_e0656824-d2d4-43ae-bebf-110186024d79.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Eine Halle voller Maschinen, Bild generiert von Midjourney</figcaption>
</figure>
</div>
<p>In diesem Teilkapitel lernen wir nun - wie angekündigt - die <em>multiple lineare Regression</em> kennen, die es erlaubt, Zusammenhänge zwischen <em>mehreren x-Variablen</em> und einer y-Variablen zu analysieren.</p>
<section id="vorbereitung-und-laden-der-daten" class="level4" data-number="0.0.1">
<h4 data-number="0.0.1" class="anchored" data-anchor-id="vorbereitung-und-laden-der-daten"><span class="header-section-number">0.0.1</span> Vorbereitung und Laden der Daten</h4>
<p>Zunächst laden wir wieder die Pakete des tidyverse und das Pakete broom um die normale Ausgabe der Funktion lm (für die Berechnung linearer Modelle) in ein etwas anschaulicheres Format umwandeln zu können. Außerdem laden wir das Paket performance, dass wir für die Voraussetzungsprüfung brauchen, sowie die Pakete lmtest und sandwich, mit der wir fehlende Voraussetzungen korrigieren können (siehe unten). Die Regression rechnen wir wieder auf Basis Allbus-Datensatzes, den wir entsprechend einlesen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(<span class="st">"pacman"</span>)) {<span class="fu">install.packages</span>(<span class="st">"pacman"</span>);<span class="fu">library</span>(pacman)}</span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="fu">p_load</span>(tidyverse, lm.beta, lmtest, performance, easystats, haven, broom, see, haven, sandwich)</span>
<span id="cb1-3"><a href="#cb1-3"></a><span class="fu">theme_set</span>(<span class="fu">theme_classic</span>())</span>
<span id="cb1-4"><a href="#cb1-4"></a></span>
<span id="cb1-5"><a href="#cb1-5"></a>daten <span class="ot">=</span> haven<span class="sc">::</span><span class="fu">read_dta</span>(<span class="st">"Datensatz/Allbus_2021.dta"</span>)</span>
<span id="cb1-6"><a href="#cb1-6"></a></span>
<span id="cb1-7"><a href="#cb1-7"></a><span class="fu">theme_set</span>(<span class="fu">theme_minimal</span>())</span>
<span id="cb1-8"><a href="#cb1-8"></a><span class="fu">options</span>(<span class="at">scipen =</span> <span class="dv">999</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="erzeugen-eines-teildatensatzes-umbenennen-der-variablen" class="level4" data-number="0.0.2">
<h4 data-number="0.0.2" class="anchored" data-anchor-id="erzeugen-eines-teildatensatzes-umbenennen-der-variablen"><span class="header-section-number">0.0.2</span> Erzeugen eines Teildatensatzes &amp; Umbenennen der Variablen</h4>
<p>Als abhängige Variable nutzen wir für unser Regressionsmodell wieder die TV-Nutzung (lm02); als unabhängige Variablen schauen wir uns wie beim letzten Mal das Alter, sowie heute zusätzlich die Variablen Bildung (educ) und Vertrauen ins Fernsehen (pt09). Damit der Output etwas nachvollziehbarer wird, benennen wir diese Variablen mit dem rename-Befehl zunächst wieder um. Außerdem filtern wir auch wieder die missings heraus (z.B. -9=Keine Angabe):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a>daten <span class="ot">&lt;-</span> daten <span class="sc">%&gt;%</span></span>
<span id="cb2-2"><a href="#cb2-2"></a>  <span class="fu">rename</span>(<span class="at">TV_Konsum =</span> lm02)<span class="sc">%&gt;%</span></span>
<span id="cb2-3"><a href="#cb2-3"></a>  <span class="fu">rename</span>(<span class="at">TV_Vertrauen=</span> pt09)<span class="sc">%&gt;%</span></span>
<span id="cb2-4"><a href="#cb2-4"></a>  <span class="fu">rename</span>(<span class="at">Alter =</span> age)<span class="sc">%&gt;%</span></span>
<span id="cb2-5"><a href="#cb2-5"></a>  <span class="fu">rename</span>(<span class="at">Bildung =</span> educ)<span class="sc">%&gt;%</span></span>
<span id="cb2-6"><a href="#cb2-6"></a>  <span class="fu">filter</span>(<span class="fu">between</span>(TV_Konsum, <span class="dv">0</span>, <span class="dv">1500</span>))<span class="sc">%&gt;%</span></span>
<span id="cb2-7"><a href="#cb2-7"></a>  <span class="fu">filter</span>(<span class="fu">between</span>(TV_Vertrauen, <span class="dv">1</span>, <span class="dv">7</span>))<span class="sc">%&gt;%</span></span>
<span id="cb2-8"><a href="#cb2-8"></a>  <span class="fu">filter</span>(<span class="fu">between</span>(Alter, <span class="dv">18</span>, <span class="dv">100</span>))<span class="sc">%&gt;%</span></span>
<span id="cb2-9"><a href="#cb2-9"></a>  <span class="fu">filter</span>(<span class="fu">between</span>(Bildung, <span class="dv">1</span>, <span class="dv">5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="erinnerung-einfache-lineare-regression-mit-alter-als-uv-und-tv-nutzung-als-av-mit-lm-linear-models" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="erinnerung-einfache-lineare-regression-mit-alter-als-uv-und-tv-nutzung-als-av-mit-lm-linear-models"><span class="header-section-number">1</span> Erinnerung: Einfache lineare Regression mit Alter als UV und TV-Nutzung als AV mit lm (=linear models)</h2>
<p>Aus den letzten Sitzungen wissen wir bereits, dass das Alter einen signifikanten, positiven Einfluss auf die TV-Nutzung hat. Wir wissen aber auch, dass die TV-Nutzung nicht alleine über das Alter erklärt werden kann (weil unser R2 recht gering war).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(TV_Konsum <span class="sc">~</span> Alter, <span class="at">data =</span> daten) </span>
<span id="cb3-2"><a href="#cb3-2"></a><span class="fu">summary</span>(<span class="fu">lm.beta</span>(model))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = TV_Konsum ~ Alter, data = daten)

Residuals:
    Min      1Q  Median      3Q     Max 
-243.01  -67.15  -22.38   34.77 1294.77 

Coefficients:
            Estimate Standardized Std. Error t value             Pr(&gt;|t|)    
(Intercept)  59.5226           NA     7.2929   8.162 0.000000000000000474 ***
Alter         2.2555       0.2970     0.1299  17.364 &lt; 0.0000000000000002 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 124.4 on 3117 degrees of freedom
Multiple R-squared:  0.0882,    Adjusted R-squared:  0.0879 
F-statistic: 301.5 on 1 and 3117 DF,  p-value: &lt; 0.00000000000000022</code></pre>
</div>
</div>
</section>
<section id="multiple-lineare-regression-mit-alter-bildung-sowie-vertrauen-ins-fernsehen-als-uv-und-tv-nutzung-als-av-mit-lm-linear-models" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="multiple-lineare-regression-mit-alter-bildung-sowie-vertrauen-ins-fernsehen-als-uv-und-tv-nutzung-als-av-mit-lm-linear-models"><span class="header-section-number">2</span> Multiple lineare Regression mit Alter, Bildung sowie Vertrauen ins Fernsehen als UV und TV-Nutzung als AV mit lm (=linear models)</h2>
<p>Mit der <em>multiplen linearen Regression</em> wollen wir nun prüfen, welche weiteren unabhängigen Variablen die TV-Nutzung erklären könnten. Dazu bringen wir Vertrauen in das Fernsehen als möglicherweise zusätzlichen erklärenden Faktor in unser Regressionsmodell ein.</p>
<p>Als Funktion können wir weiterhin lm nutzen; die zusätzlichen Variablen können wir in der Klammer ganz simpel ergänzen, indem wir sie mit einem “+” hinten anhängen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(TV_Konsum <span class="sc">~</span> Alter <span class="sc">+</span> Bildung <span class="sc">+</span> TV_Vertrauen, <span class="at">data =</span> daten) </span>
<span id="cb5-2"><a href="#cb5-2"></a><span class="fu">summary</span>(<span class="fu">lm.beta</span>(model2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = TV_Konsum ~ Alter + Bildung + TV_Vertrauen, data = daten)

Residuals:
    Min      1Q  Median      3Q     Max 
-253.27  -65.90  -19.06   33.03 1243.54 

Coefficients:
              Estimate Standardized Std. Error t value            Pr(&gt;|t|)    
(Intercept)  173.13362           NA   12.70427  13.628 &lt;0.0000000000000002 ***
Alter          1.56297      0.20579    0.13805  11.322 &lt;0.0000000000000002 ***
Bildung      -26.27887     -0.23361    1.98888 -13.213 &lt;0.0000000000000002 ***
TV_Vertrauen   5.25668      0.05248    1.71576   3.064              0.0022 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 120.9 on 3115 degrees of freedom
Multiple R-squared:  0.1383,    Adjusted R-squared:  0.1375 
F-statistic: 166.7 on 3 and 3115 DF,  p-value: &lt; 0.00000000000000022</code></pre>
</div>
</div>
<section id="inhaltliche-interpretation-des-outputs-was-bedeutet-das-ergebnis" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="inhaltliche-interpretation-des-outputs-was-bedeutet-das-ergebnis"><span class="header-section-number">2.1</span> Inhaltliche Interpretation des Outputs: Was bedeutet das Ergebnis?</h3>
<p>Der Output zeigt uns: Das Alter hat weiterhin einen positiven Einfluss auf die tägliche Fernsehnutzung in Minuten. Je älter ein Nutzer ist, desto mehr nutzt er das Fernsehen. Mit jeder Einheit, in der die unabhängige Variable Alter steigt (hier: mit jedem Jahr Alter), nimmt die unabhängige Variable TV-Konsum um 2,08 Messeinheiten (hier: Minuten) zu. Dieser Zusammenhang ist mit p=.000 statistisch höchst signifikant.</p>
<p>Auch die zweite Variable, die wir ins Regressionsmodell eingebracht haben, das Vertrauen in das Fernsehen, hat einen signifikanten, positiven Effekt auf den TV-Konsum der Befragten: Mit jedem Skalenpunkt steigt der TV-Konsum um 5,1 Minuten an. Der Einfluss des TV-Vertrauens ist hoch signifikant.</p>
<p>Schließlich hat auch der Bildungsabschluss einen höchst signifikanten Einfluss auf die Intensität der Fernsehnutzung - dieser ist allerdings negativ, so dass der TV-Konsum mit steigender Messeinheit des Bildungsniveaus sinkt. Um das zu inhaltlich interpretieren, ist es sinnvoll, sich die Skalierung der Variable genauer anzuschauen: Je höher der Wert, desto höher der Abschluss (z.B. Bildung: 1=ohne Abschluss; 3=Mittlere Reife; 5=Abitur). Wie unser Regressionsmodell zeigt, geht also ein höherer Abschluss mit einem niedrigeren TV-Konsum einher.</p>
<p>Im Output sehen wir nun auch, dass sich unser R2 (im Vergleich zur einfachen Regression oben) deutlich verbessert hat - es liegt jetzt bei 13,8 Prozent Varianzaufklärung. Das ist schon ordentlich, aber es muss immer noch weitere Faktoren geben, die die TV-Nutzung substantiell erklären können. Welche das sein können, können Sie ja mal selbst ausprobieren. Fügen Sie dazu einfach weitere - theoretisch plausible! - Kandidaten in das Regressionsmodell ein, indem sie sie durch ein “+”-Zeichen in ihre Modellfunktion integrieren (Achtung, vorher müssen Sie die zusätzlichen Variablen natürlich in ihrem Datenobjekt definieren und ggf. aufbereiten).</p>
</section>
<section id="zusätzliche-voraussetzungsprüfung-bei-der-multiplen-linearen-regression-liegt-multikollinearität-vor" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="zusätzliche-voraussetzungsprüfung-bei-der-multiplen-linearen-regression-liegt-multikollinearität-vor"><span class="header-section-number">2.2</span> Zusätzliche Voraussetzungsprüfung bei der multiplen linearen Regression: Liegt Multikollinearität vor?</h3>
<p>Die multiple lineare Regression erfordert <em>alle Voraussetzungen</em>, die für die einfache Regression auch verlangt sind - wie Sie die Voraussetzungen der Regressionaanalyse prüfen, haben Sie ja in den letzten Teilkapiteln gelernt - hier können Sie das noch einmal nachlesen:</p>
<p><a href="https://patrickzerrer.github.io/R_Hands_on_Book/Skript_7.3.html">Link</a></p>
<p>Zusätzlich müssen Sie bei einer multiplen Regresssion allerdings noch prüfen, ob <em>Multikollinearität</em> vorliegt. Multikollinearität bedeutet, dass mindestens einer unserer Prädiktoren durch einen oder mehrere der anderen Prädiktoren vorhergesagt werden kann. Die Prädiktoren wären in diesem Fall <em>nicht unabhängig</em> voneinander, sondern würden hoch miteinander korrelieren und hätten damit sozusagen <em>keine selbstständige Erklärungskraft</em> im Modell.</p>
<p>Ob Multikollinearität vorliegt, können wir durch den <em>VIF-Wert (variance inflation factor)</em> ermitteln. Dieser darf nicht über 10 liegen, idealerweise auch nicht über 5. Um dies zu prüfen, nutzen wir den check_collinearity-Befehl aus dem Performance package:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="fu">check_collinearity</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Check for Multicollinearity

Low Correlation

         Term  VIF   VIF 95% CI Increased SE Tolerance Tolerance 95% CI
        Alter 1.19 [1.15, 1.25]         1.09      0.84     [0.80, 0.87]
      Bildung 1.13 [1.09, 1.18]         1.06      0.88     [0.85, 0.92]
 TV_Vertrauen 1.06 [1.03, 1.12]         1.03      0.94     [0.90, 0.97]</code></pre>
</div>
</div>
<section id="inhaltliche-interpretation" class="level4" data-number="2.2.1">
<h4 data-number="2.2.1" class="anchored" data-anchor-id="inhaltliche-interpretation"><span class="header-section-number">2.2.1</span> Inhaltliche Interpretation</h4>
<p>Die VIF-Werte liegen zwischen 0 und 5 (sogar alle bei 1); wir können daher davon ausgehen, dass <em>keine Multikollinearität</em> vorliegt (grün = “Low Correlation”).</p>
</section>
</section>
<section id="vorhersage-des-multivariaten-modells-für-die-tägliche-tv-nutzung-durch-alter-bildung-und-vertrauen-in-das-fernsehen" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="vorhersage-des-multivariaten-modells-für-die-tägliche-tv-nutzung-durch-alter-bildung-und-vertrauen-in-das-fernsehen"><span class="header-section-number">2.3</span> Vorhersage des multivariaten Modells für die tägliche TV-Nutzung durch Alter, Bildung und Vertrauen in das Fernsehen</h3>
<p>Auch für die Kombination verschiedener Merkmale bzw. unabhängiger Variablen können wir uns über die predict.lm-Funktion Prognosen erstellen lassen. So können wir beispielsweise vergleichen, wie sich der Fernsehkonsum bestimmter “Idealtypen” von Befragten unterscheiden würde:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a><span class="fu">predict.lm</span>(model2, <span class="fu">data.frame</span>(<span class="at">Alter =</span> <span class="fu">c</span>(<span class="dv">25</span>, <span class="dv">25</span>), <span class="at">Bildung =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">5</span>), <span class="at">TV_Vertrauen =</span> <span class="fu">c</span>(<span class="dv">7</span>, <span class="dv">1</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1         2 
249.00453  86.07011 </code></pre>
</div>
</div>
<section id="inhaltliche-interpretation-was-bedeutet-der-output" class="level4" data-number="2.3.1">
<h4 data-number="2.3.1" class="anchored" data-anchor-id="inhaltliche-interpretation-was-bedeutet-der-output"><span class="header-section-number">2.3.1</span> Inhaltliche Interpretation: Was bedeutet der Output?</h4>
<p>Eine Person, die 25 Jahre alt ist und keinen Schulabschluss, aber dafür sehr großes Vertrauen in das Fernsehen hat, hat einen prognostizierten täglichen TV-Konsum von 249 Minuten. Eine Person, die ebenfalls 25 Jahre alt ist und Abitur hat, dem Fernsehen aber “überhaupt kein Vertrauen” entgegenbringt, hat einen täglichen prognostizierten Fernsehkonsum von 86 Minuten.</p>
</section>
</section>
<section id="multiple-regression-mit-dummy-codierung-der-kategorialen-variable-sex" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="multiple-regression-mit-dummy-codierung-der-kategorialen-variable-sex"><span class="header-section-number">2.4</span> Multiple Regression mit Dummy-Codierung der kategorialen Variable “sex”</h3>
<p>Eine Besonderheit schauen wir uns nun noch zum Schluss an: Die lineare Regression ist ein Verfahren für <em>metrische Daten</em>. Sie untersucht den Zusammenhang zwischen einer metrischen abhängigen Variable und mindestens einer metrischen unabhängigen Variable. In den bisherigen Regressionsanalysen haben wir mit metrischen und quasi-metrischen Variablen gearbeitet, die die Voraussetzung erfüllen, dass eine Regression gerechnet werden kann. Das ist auch der übliche Fall. Es gibt aber die “Ausnahme”, dass auch kategorische (v.a. binäre) Variablen bei der Regressionsanalyse grundsätzlich eingesetzt werden können, wenn diese durch eine <em>Dummy-Coding</em> passend gemacht werden. Und diesen Fall schauen wir un nun am Beispiel der Variable “Geschlecht” an. Dazu müssen wir die Variable aber als <em>binär codiert</em> bzw. <em>dichotom</em> betrachten - d.h. wir behandeln sie so, als hätten wir hier nur 2 Ausprägungen.</p>
<section id="vorbereitung-der-daten-zum-zusammenhang-von-alter-bildung-vertrauen-ins-tv-geschlecht-und-tv-konsum" class="level4" data-number="2.4.1">
<h4 data-number="2.4.1" class="anchored" data-anchor-id="vorbereitung-der-daten-zum-zusammenhang-von-alter-bildung-vertrauen-ins-tv-geschlecht-und-tv-konsum"><span class="header-section-number">2.4.1</span> Vorbereitung der Daten zum Zusammenhang von Alter, Bildung, Vertrauen ins TV, Geschlecht und TV-Konsum</h4>
<p>Wir wollen das biologische Geschlecht (sex) als unabhängige Variable mit in unser Regressionsmodell aufnehmen. Bei “sex” haben wir aber das Problem, dass diese Variable nicht metrisch skaliert ist. Es handelt sich vielmehr um eine kategoriale Variable (mit 3 Ausprägungen). Dennoch können wir die Variable mit einem “Trick” in die Regressionsanalyse einbringen - Sie müssen diese dann aber durch Dummy-Coding passend machen. Hier wollen uns nun mal anschauen, wie das funktioniert. Dazu müssen wir die Variable mittels mutate-Befehl aber erst einmal umcodieren und dadurch in eine dichotome VAriable verwandeln.</p>
<p>Durch die Dummy-Codierung wird die kategoriale Variable in zwei Gruppen übersetzt, von denen die eine mit 1 und die andere mit 0 codiert wird. Die Gruppe, der der Wert 0 zugeordnet wird, ist dann die Referenzkategorie. In unserem Beispiel Beispiel machen wir “männlich” zur Referenzkategorie (und codieren es mit 0 um). Der Regressionskoeffizient b gibt dann genau die Menge an, um die sich die Internetnutzung ändert, wenn sich das Geschlecht gegenüber der Referenzkategorie verändert.</p>
<p>PS: Die Variable als numerischen Wert zu behandeln, ist in unserem Fall etwas kompliziert, weil diese eine Faktorvariable war, die wir zuerst in eine Charaktervariable umwandeln mussten.</p>
</section>
<section id="dummy-codierung-der-variable-sex" class="level4" data-number="2.4.2">
<h4 data-number="2.4.2" class="anchored" data-anchor-id="dummy-codierung-der-variable-sex"><span class="header-section-number">2.4.2</span> Dummy-Codierung der Variable sex</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a>daten <span class="ot">&lt;-</span> daten <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2"></a> <span class="fu">filter</span>(<span class="fu">between</span>(sex, <span class="dv">1</span>, <span class="dv">2</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3"></a>  <span class="fu">mutate</span>(<span class="at">sex_d =</span> <span class="fu">case_when</span>(sex <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="dv">0</span>, sex <span class="sc">==</span> <span class="dv">2</span> <span class="sc">~</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="prüfung-der-umcodierung-zur-dummy-variablen" class="level4" data-number="2.4.3">
<h4 data-number="2.4.3" class="anchored" data-anchor-id="prüfung-der-umcodierung-zur-dummy-variablen"><span class="header-section-number">2.4.3</span> Prüfung der Umcodierung zur Dummy-Variablen</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a>häufigkeitstabelle <span class="ot">&lt;-</span> <span class="fu">table</span>(daten<span class="sc">$</span>sex_d)</span>
<span id="cb12-2"><a href="#cb12-2"></a><span class="fu">print</span>(häufigkeitstabelle)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   0    1 
1546 1569 </code></pre>
</div>
</div>
<p>Die Dummy-Codierung war erfolgreich - wir haben nun 1546 Befragte mit der Ausprägung 0 (männlich) sowie 1569 Befragte mit der Ausprägung 2 (weiblich).</p>
</section>
<section id="regressionsmodell-zum-zusammenhang-von-alter-bildung-tv-vertrauen-geschlecht-und-tv-konsum-spezifizieren-und-anzeigen-lassen" class="level4" data-number="2.4.4">
<h4 data-number="2.4.4" class="anchored" data-anchor-id="regressionsmodell-zum-zusammenhang-von-alter-bildung-tv-vertrauen-geschlecht-und-tv-konsum-spezifizieren-und-anzeigen-lassen"><span class="header-section-number">2.4.4</span> Regressionsmodell zum Zusammenhang von Alter, Bildung, TV-Vertrauen, Geschlecht und TV-Konsum spezifizieren und anzeigen lassen</h4>
<p>In die bereits bekannte Regressionsfunktion lm() fügen wir im hinteren Teil (d.h. hinter der Tilde) nun einfach die weitere unabhängige Variable sex_d ein, indem wir sie mit einem + Zeichen anhängen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(TV_Konsum <span class="sc">~</span> Alter <span class="sc">+</span> Bildung <span class="sc">+</span> TV_Vertrauen <span class="sc">+</span> sex_d, <span class="at">data =</span> daten) </span>
<span id="cb14-2"><a href="#cb14-2"></a><span class="fu">summary</span>(<span class="fu">lm.beta</span>(model3))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = TV_Konsum ~ Alter + Bildung + TV_Vertrauen + sex_d, 
    data = daten)

Residuals:
    Min      1Q  Median      3Q     Max 
-255.89  -64.84  -18.97   33.01 1245.99 

Coefficients:
              Estimate Standardized Std. Error t value            Pr(&gt;|t|)    
(Intercept)  170.54603           NA   12.96665  13.153 &lt;0.0000000000000002 ***
Alter          1.56629      0.20625    0.13830  11.325 &lt;0.0000000000000002 ***
Bildung      -26.32891     -0.23397    1.99103 -13.224 &lt;0.0000000000000002 ***
TV_Vertrauen   5.34102      0.05330    1.71809   3.109              0.0019 ** 
sex_d          4.60020      0.01766    4.34277   1.059              0.2896    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 121 on 3110 degrees of freedom
Multiple R-squared:  0.1386,    Adjusted R-squared:  0.1375 
F-statistic: 125.1 on 4 and 3110 DF,  p-value: &lt; 0.00000000000000022</code></pre>
</div>
</div>
</section>
<section id="inhaltliche-interpretation-des-outputs-was-bedeutet-das-ergebnis-1" class="level4" data-number="2.4.5">
<h4 data-number="2.4.5" class="anchored" data-anchor-id="inhaltliche-interpretation-des-outputs-was-bedeutet-das-ergebnis-1"><span class="header-section-number">2.4.5</span> Inhaltliche Interpretation des Outputs: Was bedeutet das Ergebnis?</h4>
<p>Gender hat <em>keinen</em> signifikanten Einfluss auf den TV-Konsum. Wenn es einen hätte, wäre der Einfluss geringer als bei Alter und Ausbildungsjahren (ersichtlich an der Größe des standardisierten beta-Koeffizienten). Wichtig: Gender ist als eine Dummy-Variable in 0=männlich und 1=weiblich codiert, deshalb ist der Estimate hier etwas schwieriger zu lesen. Die Frauen sind als 1 codiert und stellen hier die Vergleichsgruppe zur Referenzgruppe der Männer (=0) dar.</p>
<p>Frauen haben eine um (4,6) Minuten höheren TV-Konsum als Männer (wobei dieser Befund statistisch ja nicht signifikant ist). (Nicht wundern, wenn Ihr Ergebnis leicht anders ausfällt: Der Wert variiert entsprechend der gezogenen Zufallsstichprobe.)</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Handle positioning of the toggle
      window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
      const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
      for (let i=0; i<annoteTargets.length; i++) {
        const annoteTarget = annoteTargets[i];
        const targetCell = annoteTarget.getAttribute("data-target-cell");
        const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
        const contentFn = () => {
          const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          if (content) {
            const tipContent = content.cloneNode(true);
            tipContent.classList.add("code-annotation-tip-content");
            return tipContent.outerHTML;
          }
        }
        const config = {
          allowHTML: true,
          content: contentFn,
          onShow: (instance) => {
            selectCodeLines(instance.reference);
            instance.reference.classList.add('code-annotation-active');
            window.tippy.hideAll();
          },
          onHide: (instance) => {
            unselectCodeLines();
            instance.reference.classList.remove('code-annotation-active');
          },
          maxWidth: 300,
          delay: [50, 0],
          duration: [200, 0],
          offset: [5, 10],
          arrow: true,
          appendTo: function(el) {
            return el.parentElement.parentElement.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'quarto',
          placement: 'right',
          popperOptions: {
            modifiers: [
            {
              name: 'flip',
              options: {
                flipVariations: false, // true by default
                allowedAutoPlacements: ['right'],
                fallbackPlacements: ['right', 'top', 'top-start', 'top-end'],
              },
            },
            {
              name: 'preventOverflow',
              options: {
                mainAxis: false,
                altAxis: false
              }
            }
            ]        
          }      
        };
        window.tippy(annoteTarget, config); 
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Copyright 2023, Design by Katharina Maubach &amp; Patrick Zerrer</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right"><img src="Bilder/Logo_Stiftung_Hochschullehre_pos.jpg" class="img-fluid" width="120"> <img src="Bilder/Skill_UB_Icons_1_quer__blau.jpeg" class="img-fluid" width="120"></div>
  </div>
</footer>



</body></html>